<?php
if(!defined('ABSPATH'))exit;
$options=woogit_theme_options();
$plans=woogit_plans();
$features=woogit_theme_items('features_json',[]);$steps=woogit_theme_items('steps_json',[]);$faq=woogit_theme_items('faq_json',[]);
$enabled=function($key)use($options){return ($options[$key]??'1')==='1';};
$features=$features?:[['title'=>'امنیت و اعتماد','description'=>'مرز روشن بین Theme، Backend و فروشگاه مشتری.','icon'=>'◈','enabled'=>true],['title'=>'تجربه ساده','description'=>'رابط تمیز با hierarchy مشخص و بدون شلوغی.','icon'=>'▣','enabled'=>true],['title'=>'اطلاعات شفاف','description'=>'وضعیت حساب، اشتراک و سرویس در جای درست.','icon'=>'⌁','enabled'=>true]];
$steps=$steps?:[['title'=>'شروع وب','description'=>'حساب خود را از مسیر رسمی وب وارد یا ایجاد کنید.','enabled'=>true],['title'=>'انتخاب سرویس','description'=>'پلن‌ها از داده معتبر سرویس نمایش داده می‌شوند.','enabled'=>true],['title'=>'مدیریت از پرتال','description'=>'اشتراک، Billing، پرداخت‌ها و امنیت حساب را از پرتال مدیریت کنید.','enabled'=>true]];
$faq=$faq?:[['question'=>'آیا Theme به WooCommerce فروشگاه من متصل می‌شود؟','answer'=>'خیر. Theme فقط presentation و orchestration وب است.','enabled'=>true],['question'=>'اطلاعات پرداخت از کجا می‌آید؟','answer'=>'از WooCommerce خود woogit.ir و منابع authoritative سرویس.','enabled'=>true]];
$filter_enabled=function($items){return array_values(array_filter($items,function($x){return is_array($x)&&(!array_key_exists('enabled',$x)||!empty($x['enabled']));}));};
$features=$filter_enabled($features);$steps=$filter_enabled($steps);$faq=$filter_enabled($faq);
$default_tablet='https://media.easy-peasy.ai/20b11164-c351-41a4-b167-3e302745223d/905d6e89-6fc3-48da-bf19-d26197f6ed81_medium.webp';$default_mobile='https://miro.medium.com/v2/resize%3Afit%3A2048/1%2AalY3BpAQQDdSCIZpvslNxg.png';
$tablet=woogit_theme_image(absint($options['hero_image_id']??0),'large')?:$default_tablet;$mobile=woogit_theme_image(absint($options['hero_mobile_image_id']??0),'large')?:$default_mobile;
$hero_title=$options['hero_title']??'فروشگاه شما، با WooGit ساده‌تر و هوشمندتر';$hero_text=$options['hero_text']??'WooGit ابزارهایی برای مدیریت و هوشمندسازی تجربه فروشگاه ووکامرس شما فراهم می‌کند؛ با یک تجربه وب تمیز، سریع و قابل اعتماد.';$cta_text=$options['hero_cta_text']??'دریافت WooGit';$cta_url=$options['hero_cta_url']??woogit_page_url('download');$secondary_text=$options['hero_secondary_text']??'مشاهده پیش‌نمایش';$secondary_url=$options['hero_secondary_url']??'#wg-home-preview';
?>
<section class="wg-hero" id="home" aria-labelledby="wg-hero-title"><div class="wg-container wg-hero__grid"><div class="wg-hero__copy"><span class="wg-eyebrow">مدیریت هوشمند فروشگاه ووکامرس</span><h1 id="wg-hero-title"><?php echo wp_kses_post($hero_title); ?></h1><p><?php echo esc_html($hero_text); ?></p><div class="wg-actions"><a class="wg-btn wg-btn--primary wg-btn--large" href="<?php echo esc_url($cta_url); ?>"><?php echo esc_html($cta_text); ?> <span aria-hidden="true">←</span></a><a class="wg-btn wg-btn--ghost wg-btn--large" href="<?php echo esc_url($secondary_url); ?>"><?php echo esc_html($secondary_text); ?></a></div><div class="wg-hero__note">بدون ذخیره‌سازی Credentialهای فروشگاه مشتری در Theme</div></div><div class="wg-home-devices" id="wg-home-preview" aria-label="پیش‌نمایش تصویری WooGit"><div class="wg-home-motion-dot wg-dot-one" aria-hidden="true"></div><div class="wg-home-motion-dot wg-dot-two" aria-hidden="true"></div><div class="wg-home-tablet"><div class="wg-tablet-screen"><img src="<?php echo esc_url($tablet); ?>" alt="پیش‌نمایش رابط کاربری WooGit در تبلت" style="display:block;width:100%;height:100%;object-fit:cover;border-radius:21px" loading="eager" decoding="async"></div></div><div class="wg-home-mobile"><div class="wg-device-notch"></div><div class="wg-mobile-screen" style="padding:0"><img src="<?php echo esc_url($mobile); ?>" alt="پیش‌نمایش رابط کاربری WooGit در موبایل" style="display:block;width:100%;height:100%;object-fit:cover;object-position:center top;border-radius:27px" loading="eager" decoding="async"></div></div></div></div></section>
<?php if($enabled('section_features_enabled')): ?><section class="wg-section" id="features" aria-labelledby="wg-features-title"><div class="wg-container"><div class="wg-section-head"><span class="wg-eyebrow">چرا WooGit؟</span><h2 id="wg-features-title">یک تجربه ساده برای یک محصول جدی</h2><p><?php echo esc_html($options['features_intro']??'هویت مدرن، hierarchy واضح و تمرکز روی کاری که واقعاً برای شما مهم است.'); ?></p></div><div class="wg-grid wg-grid--3 wg-reference-features"><?php foreach(array_slice($features,0,6) as $feature):$image=woogit_theme_image(absint($feature['image_id']??0),'thumbnail');?><article class="wg-card"><div class="wg-icon" aria-hidden="true"><?php if($image):?><img src="<?php echo esc_url($image);?>" alt="" loading="lazy" width="56" height="56"><?php else:echo esc_html($feature['icon']??'✦');endif;?></div><h3><?php echo esc_html($feature['title']??'');?></h3><p><?php echo esc_html($feature['description']??($feature['text']??''));?></p></article><?php endforeach;?></div></div></section><?php endif;?>
<?php if($enabled('section_how_enabled')): ?><section class="wg-section wg-steps" id="how" aria-labelledby="wg-how-title"><div class="wg-container"><div class="wg-section-head"><span class="wg-eyebrow">نحوه کار</span><h2 id="wg-how-title">مسیر شروع، کوتاه و روشن</h2><p><?php echo esc_html($options['how_it_works_intro']??'جزئیات امنیتی و business truth در Backend باقی می‌ماند.');?></p></div><div class="wg-grid wg-grid--3"><?php foreach(array_slice($steps,0,6) as $i=>$step):$image=woogit_theme_image(absint($step['image_id']??0),'thumbnail');?><article class="wg-card"><div class="wg-step-number"><?php echo esc_html((string)($i+1));?></div><?php if($image):?><img src="<?php echo esc_url($image);?>" alt="" loading="lazy" style="width:100%;height:120px;object-fit:cover;border-radius:12px;margin:8px 0 14px"><?php endif;?><h3><?php echo esc_html($step['title']??'');?></h3><p><?php echo esc_html($step['description']??($step['text']??''));?></p><?php if(!empty($step['url'])):?><a class="wg-btn wg-btn--ghost" href="<?php echo esc_url($step['url']);?>">ادامه</a><?php endif;?></article><?php endforeach;?></div></div></section><?php endif;?>
<?php if($enabled('section_app_enabled')): ?><section class="wg-section wg-app-section" aria-labelledby="wg-app-title"><div class="wg-container"><div class="wg-home-app"><div class="wg-home-mini-devices" aria-label="پیش‌نمایش محصول WooGit"><div class="wg-home-mini-tablet"><div class="wg-mini-content"><strong>WooGit</strong><div></div><div></div><div></div></div></div><div class="wg-home-mini-phone"><div class="wg-mini-phone-content"><strong>WooGit</strong><span>فروشگاه متصل</span><span>اشتراک حرفه‌ای</span><span>وضعیت حساب</span></div></div></div><div class="wg-home-app__copy"><span class="wg-eyebrow">محصول WooGit</span><h2 id="wg-app-title">یک هویت مشترک برای وب و محصول</h2><p><?php echo esc_html($options['documentation_intro']??'Theme فقط لایه وب است؛ عملیات فروشگاه مشتری متعلق به App و حقیقت، مجوز و امنیت متعلق به Backend است.');?></p><a class="wg-btn wg-btn--ghost" href="<?php echo esc_url(woogit_page_url('documentation'));?>">آشنایی با مستندات</a></div></div></div></section><?php endif;?>
<?php if($enabled('section_pricing_enabled')): ?><section class="wg-section" id="pricing" aria-labelledby="wg-pricing-title"><div class="wg-container"><div class="wg-section-head"><span class="wg-eyebrow">قیمت‌گذاری</span><h2 id="wg-pricing-title">پلن مناسب خودتان را انتخاب کنید</h2><p><?php echo esc_html($options['pricing_intro']??'قیمت، مدت، قابلیت‌ها و محدودیت‌ها در نسخه واقعی از داده قراردادی دریافت می‌شوند.');?></p></div><div class="wg-grid wg-grid--3 wg-pricing-grid"><?php if($plans):foreach(array_slice($plans,0,3) as $i=>$plan):$featured=$i===1;?><article class="wg-card wg-plan <?php echo $featured?'wg-plan--featured':'';?>"><span class="wg-plan__badge"><?php echo $featured?'پیشنهاد اصلی':'WooGit';?></span><h3><?php echo esc_html($plan['name']??$plan['title']??'پلن WooGit');?></h3><div class="wg-plan__price"><?php echo esc_html($plan['price']??'');?> <small><?php echo esc_html($plan['currency']??'');?></small></div><p><?php echo esc_html($plan['description']??'برای استفاده از WooGit.');?></p><a class="wg-btn <?php echo $featured?'':'wg-btn--ghost';?>" href="<?php echo esc_url(woogit_page_url('login'));?>">انتخاب پلن</a></article><?php endforeach;else:?><article class="wg-card wg-plan"><span class="wg-plan__badge">اطلاعات سرویس</span><h3>قیمت‌گذاری در دسترس نیست</h3><div class="wg-plan__price">—</div><p>داده معتبر قیمت‌گذاری از Commerce در دسترس نیست.</p><a class="wg-btn wg-btn--ghost" href="<?php echo esc_url(woogit_page_url('support'));?>">پشتیبانی</a></article><?php endif;?></div></div></section><?php endif;?>
<?php if($enabled('section_faq_enabled')): ?><section class="wg-section wg-faq" id="faq" aria-labelledby="wg-faq-title"><div class="wg-container"><div class="wg-section-head"><span class="wg-eyebrow">سؤالات متداول</span><h2 id="wg-faq-title">پاسخ‌های کوتاه، قبل از شروع</h2><p><?php echo esc_html($options['faq_intro']??'');?></p></div><div class="wg-faq__list"><?php foreach(array_slice($faq,0,12) as $item):?><details class="wg-faq__item"><summary><?php echo esc_html($item['question']??'');?></summary><p><?php echo esc_html($item['answer']??'');?></p></details><?php endforeach;?></div></div></section><?php endif;?>
<section class="wg-cta"><div class="wg-container"><div><span class="wg-eyebrow">شروع کنید</span><h2>آماده‌اید WooGit را شروع کنید؟</h2><p><?php echo esc_html($options['support_intro']??'مسیر رسمی ثبت‌نام و دریافت محصول را دنبال کنید.');?></p></div><a class="wg-btn wg-btn--primary" href="<?php echo esc_url(woogit_page_url('register'));?>">ایجاد حساب</a></div></section>
