#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PLUGIN="$ROOT/plugin/woogit-backend"
fail(){ echo "FAIL: $1" >&2; exit 1; }
contains(){ local file="$1" pattern="$2" label="$3"; grep -Eq "$pattern" "$file" || fail "$label"; }
while IFS= read -r -d '' file; do php -l "$file" >/dev/null || fail "PHP syntax: $file"; done < <(find "$PLUGIN" -type f -name '*.php' -print0)
controller="$PLUGIN/src/RestController.php"; billingController="$PLUGIN/src/BillingController.php"; billing="$PLUGIN/src/BillingService.php"; policy="$PLUGIN/src/ProxyPolicy.php"; proxy="$PLUGIN/src/WooCommerceProxy.php"; idempotency="$PLUGIN/src/IdempotencyService.php"; operations="$PLUGIN/src/OperationService.php"; database="$PLUGIN/src/Database.php"; account="$PLUGIN/src/AccountService.php"; identity="$PLUGIN/src/IdentityService.php"; site="$PLUGIN/src/SiteService.php"; bootstrap="$PLUGIN/woogit-backend.php"; rate="$PLUGIN/src/RateLimitService.php"; version="$PLUGIN/src/VersionGate.php"; versionAdmin="$PLUGIN/src/VersionAdmin.php"; announcement="$PLUGIN/src/AnnouncementService.php"; announcementController="$PLUGIN/src/AnnouncementController.php"; announcementAdmin="$PLUGIN/src/AnnouncementAdmin.php"; webSession="$PLUGIN/src/WebSessionService.php"; webAuth="$PLUGIN/src/WebAuthController.php"; requirement="$PLUGIN/src/RequirementService.php"
contains "$controller" 'getOwned' 'controller must enforce Site ownership'
contains "$controller" 'X-WooGit-Session' 'controller must require WooGit Session'
contains "$controller" 'APP_VERSION_DEPRECATED' 'controller must enforce deprecated-version gate'
contains "$controller" 'RATE_LIMITED' 'controller must enforce rate limiting'
contains "$controller" 'request_body_too_large' 'controller must enforce request body size'
contains "$controller" 'validateMethod' 'controller must validate mutation method/idempotency'
contains "$controller" 'operation_status_unknown' 'controller must expose unknown operation state'
contains "$controller" 'requires_reconciliation' 'controller must mark unknown operations as requiring reconciliation'
contains "$controller" 'Idempotency-Key' 'site verification must require idempotency'
contains "$controller" 'lookupVerify' 'site verification must lookup idempotency before side effects'
contains "$controller" 'claimVerify' 'site verification must atomically claim idempotency'
contains "$controller" 'completeVerify' 'site verification must persist terminal result'
contains "$idempotency" 'sodium_crypto_secretbox' 'verify replay payload must be encrypted at rest'
contains "$operations" 'bindContext' 'verify operation must bind to the created Account/Site'
contains "$billingController" 'RateLimitService' 'billing controller must use shared RateLimitService'
contains "$billingController" "billing_plans_ip" 'billing plans must be IP rate limited'
contains "$billingController" 'PLANS_LIMIT = 60' 'billing plans limit must be 60/min'
contains "$billingController" "billing_status_account_site" 'billing status must be Account/Site rate limited'
contains "$billingController" "billing_status_session" 'billing status must be Session rate limited'
contains "$billingController" 'STATUS_LIMIT = 30' 'billing status must be 30/min'
contains "$billingController" "billing_checkout_account_site" 'billing checkout must be Account/Site rate limited'
contains "$billingController" "billing_checkout_ip" 'billing checkout must be IP rate limited'
contains "$billingController" 'CHECKOUT_LIMIT = 5' 'billing checkout limit must be 5/min'
contains "$billingController" "billing_activate_session_account_site" 'billing activation must be Account/Site rate limited'
contains "$billingController" "billing_activate_session_session" 'billing activation must be Session rate limited'
contains "$billingController" "billing_activate_session_ip" 'billing activation must be IP rate limited'
contains "$billingController" 'ACTIVATE_SESSION_LIMIT = 5' 'billing activation limit must be 5/min'
contains "$billingController" 'WINDOW_SECONDS = 60' 'billing billing window must be 60 seconds'
contains "$billingController" 'Retry-After' 'billing rate limiting must expose Retry-After'
grep -Fq "hash('sha256'" "$billingController" || fail 'billing must not persist raw session tokens as rate-limit keys'
contains "$billing" 'getPaymentHistory' 'billing service must expose account payment history'
contains "$billing" "_woogit_account_id" 'payment history must be scoped to WooGit Account metadata'
contains "$billing" "_woogit_site_id" 'payment history must be scoped to Site metadata'
contains "$idempotency" 'state.*unknown' 'idempotency must support unknown state'
contains "$proxy" 'wp_safe_remote_request' 'proxy must use safe WordPress HTTP request'
contains "$proxy" 'resolvePublicDestination' 'proxy must validate resolved public destination'
contains "$proxy" 'NO_PRIV_RANGE' 'proxy must reject private/reserved destinations'
contains "$proxy" 'DNS_AAAA' 'proxy must inspect IPv6 DNS records'
contains "$proxy" 'records===\[\]' 'proxy must fail closed when DNS does not resolve'
contains "$proxy" 'foreach\(\$this->pinnedIps' 'proxy must pin all validated public IPs'
contains "$proxy" 'immediately before the HTTP call' 'proxy must resolve immediately before connecting'
contains "$policy" 'https' 'policy must enforce HTTPS'
contains "$proxy" "'redirection'=>0" 'proxy must not follow upstream redirects'
contains "$policy" 'site identity is the origin' 'site identity must be normalized to origin'
if grep -Eq 'consumer_(key|secret).*query|query.*consumer_(key|secret)' "$proxy"; then fail 'credentials must not be query parameters'; fi
contains "$database" 'UNIQUE KEY host \(host\)' 'Site host must be globally unique'
contains "$database" 'UNIQUE KEY account_id \(account_id\)' 'Account must have exactly one Site relationship'
contains "$database" 'UNIQUE KEY wp_user_id \(wp_user_id\)' 'WordPress identity must map to at most one WooGit Account'
contains "$database" 'migrateAccountIdentity' 'identity migration must be versioned'
contains "$site" 'one-to-one with the connected site' 'SiteService must enforce one-site-per-account invariant'
contains "$account" 'function create' 'Account must be created explicitly'
contains "$account" 'createCustomer' 'Account creation must create the single WP/WooCommerce customer identity'
contains "$account" 'function updateContactEmail' 'Account contact email update must be explicit'
contains "$account" 'wp_user_id' 'Account must expose its linked WordPress identity'
if grep -Eq 'email_exists|findByEmail' "$account" "$identity" "$controller"; then fail 'email must never participate in identity lookup or linking'; fi
contains "$identity" 'function createCustomer' 'verified Account lifecycle must create a central customer identity'
contains "$identity" "'user_email'=>''" 'customer identity creation must not require contact email'
contains "$identity" 'wp_insert_user' 'customer identity must be a WordPress user'
contains "$identity" "'role'=>'customer'" 'customer identity must use the WooCommerce customer role'
contains "$identity" 'WEB_PASSWORD_META' 'web password configuration must be separate from customer identity existence'
contains "$identity" 'wp_check_password' 'web password verification must use WordPress password hashing'
contains "$identity" 'wp_set_password' 'web password changes must use WordPress password storage'
if grep -Eq 'linkOrCreate|current_wordpress_password|identity_verification_required|email_exists' "$identity" "$webAuth"; then fail 'web setup must not claim or link identities by contact email'; fi
if grep -Eq "'email'.*email_exists|email_exists.*'email'" "$controller" "$account" "$identity"; then fail 'contact email must not be an identity lookup key'; fi
contains "$database" 'web_sessions' 'web authentication must use a separate session table'
contains "$webSession" 'token_hash' 'web sessions must store token hashes'
contains "$webSession" 'random_bytes' 'web session tokens must be cryptographically random'
contains "$webAuth" "'/web/login'" 'web login endpoint must exist'
contains "$webAuth" "'/web/logout'" 'web logout endpoint must exist'
contains "$webAuth" "'/web/me'" 'web session identity endpoint must exist'
contains "$webAuth" "'/web/account/contact-email'" 'web contact email management endpoint must exist'
contains "$webAuth" "'/web/account/password'" 'web password change endpoint must exist'
contains "$webAuth" "'/web/billing/history'" 'web payment history endpoint must exist'
contains "$webAuth" "'/account/requirements'" 'account requirements endpoint must exist'
contains "$webAuth" "'/account/setup-web-credentials'" 'web credential setup endpoint must exist'
contains "$webAuth" 'site_url' 'web login identity must use Site URL'
contains "$webAuth" 'password' 'web login must use password'
contains "$webAuth" 'invalid_web_credentials' 'web login failures must be generic'
contains "$webAuth" 'web_login_ip' 'web login must be IP rate limited'
contains "$webAuth" 'web_login_site' 'web login must be Site/host rate limited'
contains "$webAuth" 'X-WooGit-Web-Session' 'web API must use a separate session credential'
contains "$webAuth" 'identity_user_id' 'web identity must expose the linked WordPress user id'
contains "$bootstrap" 'IdentityService' 'WordPress identity service must be bootstrapped'
contains "$bootstrap" 'WebSessionService' 'web session service must be bootstrapped'
contains "$bootstrap" 'WebAuthController' 'web auth controller must be registered'
contains "$bootstrap" "woogit_idempotency WHERE updated_at < .*AND state IN \('succeeded','failed'\)" 'retention must never delete pending/unknown idempotency rows'
contains "$bootstrap" "woogit_operations WHERE expires_at IS NOT NULL .*status IN \('succeeded','failed'\)" 'operation retention must preserve unknown operations'
contains "$bootstrap" 'woogit_web_sessions WHERE expires_at <' 'expired web sessions must be cleaned up'
contains "$idempotency" 'state.*pending' 'idempotency must support pending state'
contains "$operations" 'markUnknown' 'operation service must persist unknown state'
contains "$rate" 'ON DUPLICATE KEY UPDATE' 'rate limit counter must be atomic'
contains "$rate" 'allowed.*false' 'rate limit must fail closed on storage error'
contains "$version" 'APP_VERSION_REQUIRED' 'version gate must reject missing app version'
if grep -Eq "if\(\$version===''\).*allowed.*true|if\(\$version===''\)return \['allowed'=>true" "$version"; then fail 'version gate must not allow missing app version'; fi
contains "$version" 'minimum_supported_version' 'version gate must enforce minimum supported version'
contains "$version" 'deprecated_versions' 'version gate must support explicit deprecated versions'
contains "$database" 'version_compare' 'database migrations must be version gated'
contains "$database" 'false===\$result' 'database migrations must stop on failed schema alteration'
contains "$versionAdmin" 'manage_options' 'version policy admin must require administrator capability'
contains "$versionAdmin" 'check_admin_referer' 'version policy changes must require CSRF nonce'
contains "$versionAdmin" 'VERSION_PATTERN' 'version policy admin must validate version syntax'
contains "$versionAdmin" 'update_option(self::OPTION' 'version policy admin must persist through WordPress options API'
contains "$bootstrap" 'VersionAdmin' 'version policy admin must be registered by plugin bootstrap'
# Use character classes for literal parentheses. This avoids grep -E's special
# meaning for escaped grouping syntax (\(...), which previously caused an
# "Unmatched ( or \(" failure on the CI runner.
contains "$versionAdmin" 'version_compare[(]\$minimum, \$latest' 'minimum supported version must not exceed latest version'
contains "$versionAdmin" 'version_compare[(]\$recommended, \$latest' 'recommended version must not exceed latest version'
contains "$versionAdmin" 'version_compare[(]\$recommended, \$minimum' 'recommended version must not be below minimum supported version'
contains "$announcement" 'active' 'announcement service must filter active records'
contains "$announcement" 'app_versions' 'announcements must support app-version targeting'
contains "$announcementAdmin" 'display_type' 'announcement admin must persist numeric app-owned display type'
contains "$announcementController" "'/announcements'" 'announcement endpoint must be registered'
contains "$announcementController" 'VersionGate' 'announcement endpoint must understand app versions'
contains "$announcementController" 'APP_VERSION_REQUIRED' 'announcement endpoint must reject missing app version'
contains "$announcementController" 'system-app-version-deprecated' 'deprecated app must receive an in-app update banner'
contains "$announcementController" 'system-entitlement-expiring' 'expiring entitlement must receive an in-app warning'
contains "$announcementAdmin" 'manage_options' 'announcement admin must require administrator capability'
contains "$announcementAdmin" 'check_admin_referer' 'announcement changes must require CSRF nonce'
contains "$bootstrap" 'AnnouncementController' 'announcement controller must be registered by plugin bootstrap'
contains "$bootstrap" 'AnnouncementAdmin' 'announcement admin must be registered by plugin bootstrap'
contains "$requirement" 'TYPE_WEB_ACCOUNT_PASSWORD = 1' 'web password requirement type must be numeric and stable'
contains "$requirement" 'TYPE_CONTACT_EMAIL = 2' 'contact email requirement type must be numeric and stable'
contains "$requirement" 'numeric type is an opaque wire value' 'requirement type contract must be app-owned'
contains "$webAuth" 'requirements->build' 'requirements endpoint must use generic requirement service'
if grep -Eq "'type'=>'(account_setup|contact_metadata)'" "$webAuth"; then fail 'requirements endpoint must not emit string semantic types'; fi
contains "$bootstrap" 'RequirementService' 'generic requirement service must be bootstrapped'
echo "security invariants: PASS"
