#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PLUGIN="$ROOT/plugin/woogit-backend"
fail(){ echo "FAIL: $1" >&2; exit 1; }
contains(){ local file="$1" pattern="$2" label="$3"; grep -Eq "$pattern" "$file" || fail "$label"; }

while IFS= read -r -d '' file; do
  echo "CHECK PHP: $file"
  php -l "$file" >/dev/null || fail "PHP syntax: $file"
done < <(find "$PLUGIN" -type f -name '*.php' -print0)
controller="$PLUGIN/src/RestController.php"; billingController="$PLUGIN/src/BillingController.php"; policy="$PLUGIN/src/ProxyPolicy.php"; proxy="$PLUGIN/src/WooCommerceProxy.php"; idempotency="$PLUGIN/src/IdempotencyService.php"; operations="$PLUGIN/src/OperationService.php"; database="$PLUGIN/src/Database.php"; account="$PLUGIN/src/AccountService.php"; site="$PLUGIN/src/SiteService.php"; bootstrap="$PLUGIN/woogit-backend.php"; rate="$PLUGIN/src/RateLimitService.php"; version="$PLUGIN/src/VersionGate.php"; versionAdmin="$PLUGIN/src/VersionAdmin.php"; announcement="$PLUGIN/src/AnnouncementService.php"; announcementController="$PLUGIN/src/AnnouncementController.php"; announcementAdmin="$PLUGIN/src/AnnouncementAdmin.php"; webSession="$PLUGIN/src/WebSessionService.php"; webAuth="$PLUGIN/src/WebAuthController.php"

echo "CHECK controller ownership"; contains "$controller" 'getOwned' 'controller must enforce Site ownership'
echo "CHECK controller session"; contains "$controller" 'X-WooGit-Session' 'controller must require WooGit Session'
echo "CHECK controller version gate"; contains "$controller" 'APP_VERSION_DEPRECATED' 'controller must enforce deprecated-version gate'
echo "CHECK controller rate limit"; contains "$controller" 'RATE_LIMITED' 'controller must enforce rate limiting'
echo "CHECK controller body limit"; contains "$controller" 'request_body_too_large' 'controller must enforce request body size'
echo "CHECK controller mutation validation"; contains "$controller" 'validateMethod' 'controller must validate mutation method/idempotency'
echo "CHECK controller unknown operation"; contains "$controller" 'operation_status_unknown' 'controller must expose unknown operation state'
echo "CHECK controller reconciliation"; contains "$controller" 'requires_reconciliation' 'controller must mark unknown operations as requiring reconciliation'
echo "CHECK verify idempotency"; contains "$controller" 'Idempotency-Key' 'site verification must require idempotency'
contains "$controller" 'lookupVerify' 'site verification must lookup idempotency before side effects'
contains "$controller" 'claimVerify' 'site verification must atomically claim idempotency'
contains "$controller" 'completeVerify' 'site verification must persist terminal result'
contains "$idempotency" 'sodium_crypto_secretbox' 'verify replay payload must be encrypted at rest'
contains "$operations" 'bindContext' 'verify operation must bind to the created Account/Site'
echo "CHECK billing rate limit service"; contains "$billingController" 'RateLimitService' 'billing controller must use shared RateLimitService'
echo "CHECK billing plans IP limit"; contains "$billingController" "billing_plans_ip" 'billing plans must be IP rate limited'
contains "$billingController" 'PLANS_LIMIT = 60' 'billing plans limit must be 60/min'
echo "CHECK billing status identity limits"; contains "$billingController" "billing_status_account_site" 'billing status must be Account/Site rate limited'
contains "$billingController" "billing_status_session" 'billing status must be Session rate limited'
contains "$billingController" 'STATUS_LIMIT = 30' 'billing status limit must be 30/min'
echo "CHECK billing checkout limits"; contains "$billingController" "billing_checkout_account_site" 'billing checkout must be Account/Site rate limited'
contains "$billingController" "billing_checkout_ip" 'billing checkout must be IP rate limited'
contains "$billingController" 'CHECKOUT_LIMIT = 5' 'billing checkout limit must be 5/min'
echo "CHECK billing activation limits"; contains "$billingController" "billing_activate_session_account_site" 'billing activation must be Account/Site rate limited'
contains "$billingController" "billing_activate_session_session" 'billing activation must be Session rate limited'
contains "$billingController" "billing_activate_session_ip" 'billing activation must be IP rate limited'
contains "$billingController" 'ACTIVATE_SESSION_LIMIT = 5' 'billing activation limit must be 5/min'
contains "$billingController" 'WINDOW_SECONDS = 60' 'billing billing window must be 60 seconds'
echo "CHECK billing rate limit response"; contains "$billingController" 'Retry-After' 'billing rate limiting must expose Retry-After'
echo "CHECK billing session key hashing"; grep -Fq "hash('sha256'" "$billingController" || fail 'billing must not persist raw session tokens as rate-limit keys'
echo "CHECK idempotency states"; contains "$idempotency" 'state.*unknown' 'idempotency must support unknown state'
echo "CHECK safe HTTP"; contains "$proxy" 'wp_safe_remote_request' 'proxy must use safe WordPress HTTP request'
echo "CHECK resolved destination"; contains "$proxy" 'resolvePublicDestination' 'proxy must validate resolved public destination'
echo "CHECK private ranges"; contains "$proxy" 'NO_PRIV_RANGE' 'proxy must reject private/reserved destinations'
echo "CHECK IPv4/IPv6 DNS"; contains "$proxy" 'DNS_AAAA' 'proxy must inspect IPv6 DNS records'
echo "CHECK DNS fail closed"; contains "$proxy" 'records===\[\]' 'proxy must fail closed when DNS does not resolve'
echo "CHECK DNS multi-IP pinning"; contains "$proxy" 'foreach\(\$this->pinnedIps' 'proxy must pin all validated public IPs'
echo "CHECK per-request resolution"; contains "$proxy" 'immediately before the HTTP call' 'proxy must resolve immediately before connecting'
echo "CHECK HTTPS"; contains "$policy" 'https' 'policy must enforce HTTPS'
echo "CHECK redirect disabled"; contains "$proxy" "'redirection'=>0" 'proxy must not follow upstream redirects'
echo "CHECK origin-only site identity"; contains "$policy" 'site identity is the origin' 'site identity must be normalized to origin'
if grep -Eq 'consumer_(key|secret).*query|query.*consumer_(key|secret)' "$proxy"; then fail 'credentials must not be query parameters'; fi
echo "CHECK global site host uniqueness"; contains "$database" 'UNIQUE KEY host \(host\)' 'Site host must be globally unique'
echo "CHECK one account one site"; contains "$database" 'UNIQUE KEY account_id \(account_id\)' 'Account must have exactly one Site relationship'
contains "$site" 'one-to-one with the connected site' 'SiteService must enforce one-site-per-account invariant'
echo "CHECK explicit account creation"; contains "$account" 'function create' 'Account must be created explicitly'
echo "CHECK contact email update"; contains "$account" 'function updateContactEmail' 'Account contact email update must be explicit'
contains "$account" 'web_password_hash' 'Account must store only the web password hash'
contains "$account" 'PASSWORD_ARGON2ID' 'web password must use Argon2id hashing'
contains "$account" 'password_verify' 'web password login must verify a hash'
if grep -Eq 'findOrCreate\([^)]*email|findOrCreate\(\$email' "$account" "$controller"; then fail 'email must never resolve Account identity'; fi
echo "CHECK web session separation"; contains "$database" 'web_sessions' 'web authentication must use a separate session table'
contains "$webSession" 'token_hash' 'web sessions must store token hashes'
contains "$webSession" 'random_bytes' 'web session tokens must be cryptographically random'
contains "$webAuth" "'/web/login'" 'web login endpoint must exist'
contains "$webAuth" "'/web/logout'" 'web logout endpoint must exist'
contains "$webAuth" "'/web/me'" 'web session identity endpoint must exist'
contains "$webAuth" "'/account/requirements'" 'account requirements endpoint must exist'
contains "$webAuth" "'/account/setup-web-credentials'" 'web credential setup endpoint must exist'
contains "$webAuth" "site_url" 'web login identity must use Site URL'
contains "$webAuth" "password" 'web login must use password'
contains "$webAuth" 'invalid_web_credentials' 'web login failures must be generic'
contains "$webAuth" 'web_login_ip' 'web login must be IP rate limited'
contains "$webAuth" 'web_login_site' 'web login must be Site/host rate limited'
contains "$webAuth" 'X-WooGit-Web-Session' 'web API must use a separate session credential'
contains "$bootstrap" 'WebSessionService' 'web session service must be bootstrapped'
contains "$bootstrap" 'WebAuthController' 'web auth controller must be registered'
echo "CHECK idempotency retention"; contains "$bootstrap" "woogit_idempotency WHERE updated_at < .*AND state IN \('succeeded','failed'\)" 'retention must never delete pending/unknown idempotency rows'
echo "CHECK operation retention"; contains "$bootstrap" "woogit_operations WHERE expires_at IS NOT NULL .*status IN \('succeeded','failed'\)" 'operation retention must preserve unknown operations'
echo "CHECK web session retention"; contains "$bootstrap" 'woogit_web_sessions WHERE expires_at <' 'expired web sessions must be cleaned up'
echo "CHECK pending state"; contains "$idempotency" 'state.*pending' 'idempotency must support pending state'
echo "CHECK unknown persistence"; contains "$operations" 'markUnknown' 'operation service must persist unknown state'
echo "CHECK atomic rate limit"; contains "$rate" 'ON DUPLICATE KEY UPDATE' 'rate limit counter must be atomic'
echo "CHECK fail-closed rate limit"; contains "$rate" 'allowed.*false' 'rate limit must fail closed on storage error'
echo "CHECK minimum version"; contains "$version" 'minimum_supported_version' 'version gate must enforce minimum supported version'
echo "CHECK deprecated versions"; contains "$version" 'deprecated_versions' 'version gate must support explicit deprecated versions'
echo "CHECK versioned migrations"; contains "$database" 'version_compare' 'database migrations must be version gated'
echo "CHECK migration failure guard"; contains "$database" 'false===\$result' 'database migrations must stop on failed schema alteration'
echo "CHECK version admin capability"; contains "$versionAdmin" 'manage_options' 'version policy admin must require administrator capability'
echo "CHECK version admin nonce"; contains "$versionAdmin" 'check_admin_referer' 'version policy changes must require CSRF nonce'
echo "CHECK version admin validation"; contains "$versionAdmin" 'VERSION_PATTERN' 'version policy admin must validate version syntax'
echo "CHECK version admin safe update"; contains "$versionAdmin" "update_option\(self::OPTION" 'version policy admin must persist through WordPress options API'
echo "CHECK version admin registration"; contains "$bootstrap" 'VersionAdmin' 'version policy admin must be registered by plugin bootstrap'
echo "CHECK version admin constraints"; contains "$versionAdmin" 'minimum.*latest' 'version policy admin must enforce minimum/latest ordering'
echo "CHECK announcement service"; contains "$announcement" 'display_type' 'announcements must carry an app-owned display type'
contains "$announcement" 'active' 'announcement service must filter active records'
contains "$announcement" 'app_versions' 'announcements must support app-version targeting'
echo "CHECK announcement endpoint"; contains "$announcementController" "'/announcements'" 'announcement endpoint must be registered'
contains "$announcementController" 'VersionGate' 'announcement endpoint must understand deprecated app versions'
contains "$announcementController" 'system-app-version-deprecated' 'deprecated app must receive an in-app update banner'
contains "$announcementController" 'system-entitlement-expiring' 'expiring entitlement must receive an in-app warning'
echo "CHECK announcement admin"; contains "$announcementAdmin" 'manage_options' 'announcement admin must require administrator capability'
contains "$announcementAdmin" 'check_admin_referer' 'announcement changes must require CSRF nonce'
contains "$announcementAdmin" 'display_type' 'announcement admin must expose numeric display type'
contains "$bootstrap" 'AnnouncementController' 'announcement controller must be registered by plugin bootstrap'
contains "$bootstrap" 'AnnouncementAdmin' 'announcement admin must be registered by plugin bootstrap'

echo "security invariants: PASS"