<?php
namespace WooGit\Backend;
defined('ABSPATH') || exit;

final class AccountsAdmin
{
    private const ACTION='woogit_account_admin_action';
    public function register():void{add_menu_page('WooGit Accounts','WooGit Accounts','manage_options','woogit-accounts',[$this,'render'],'dashicons-admin-users',56);}
    public function render():void{
        if(!current_user_can('manage_options'))wp_die('دسترسی غیرمجاز.');
        $notice=$this->action();global $wpdb;
        $a=$wpdb->prefix.'woogit_accounts';$s=$wpdb->prefix.'woogit_sites';$u=$wpdb->users;$e=$wpdb->prefix.'woogit_entitlements';
        $q=isset($_GET['s'])?sanitize_text_field(wp_unslash((string)$_GET['s'])):'';$where='';
        if($q!==''){$like='%'.$wpdb->esc_like($q).'%';$where=$wpdb->prepare(' WHERE a.email LIKE %s OR s.host LIKE %s OR u.user_login LIKE %s OR CAST(a.id AS CHAR) LIKE %s ',$like,$like,$like,$like);}
        $rows=$wpdb->get_results("SELECT a.*,u.user_login,u.display_name,s.id site_id,s.canonical_url,s.host,s.status site_status,e.status entitlement_status,e.starts_at,e.expires_at,e.capabilities FROM {$a} a LEFT JOIN {$u} u ON u.ID=a.wp_user_id LEFT JOIN {$s} s ON s.account_id=a.id LEFT JOIN {$e} e ON e.account_id=a.id AND e.site_id=s.id {$where} ORDER BY a.id DESC",ARRAY_A);
        $plans=$this->plans();
        ?><div class="wrap"><h1>WooGit Accounts</h1><p>پنل کامل مدیریت حساب، سایت، هویت، دسترسی، Trial و بسته‌ها.</p>
        <?php if($notice):?><div class="notice notice-<?php echo esc_attr($notice[0]);?> is-dismissible"><p><?php echo esc_html($notice[1]);?></p></div><?php endif;?>
        <form method="get" style="margin:16px 0"><input type="hidden" name="page" value="woogit-accounts"><input type="search" name="s" value="<?php echo esc_attr($q);?>" placeholder="Account ID، دامنه، username یا email" style="min-width:380px"><button class="button">جستجو</button></form>
        <table class="widefat striped"><thead><tr><th>Account</th><th>Identity</th><th>Site</th><th>Package</th><th>Status</th><th>مدیریت</th></tr></thead><tbody>
        <?php if(!$rows):?><tr><td colspan="6">حسابی پیدا نشد.</td></tr><?php else:foreach($rows as $r):$caps=json_decode((string)$r['capabilities'],true);$caps=is_array($caps)?$caps:[];?><tr>
        <td><strong>#<?php echo esc_html($r['id']);?></strong><br><small>Created <?php echo esc_html($r['created_at']);?></small><br><small>Updated <?php echo esc_html($r['updated_at']);?></small></td>
        <td><?php echo $r['wp_user_id']?'WP ID '.esc_html($r['wp_user_id']).'<br><code>'.esc_html($r['user_login']??'').'</code>':'بدون Identity';?><br><?php echo esc_html($r['email']?:'بدون ایمیل');?><br><small><?php echo $r['trial_used_at']?'Trial مصرف شده':'Trial قابل استفاده';?></small></td>
        <td><?php if($r['site_id']):?><a href="<?php echo esc_url($r['canonical_url']);?>" target="_blank" rel="noopener"><?php echo esc_html($r['host']);?></a><br><small><?php echo esc_html($r['site_status']);?></small><?php else:?>بدون سایت<?php endif;?></td>
        <td><?php echo esc_html($r['entitlement_status']?:'none');?><br><small><?php echo $r['expires_at']?'تا '.esc_html($r['expires_at']):'بدون اعتبار';?></small><br><small><?php echo esc_html(implode(', ',$caps));?></small></td>
        <td><strong><?php echo esc_html($r['status']);?></strong></td><td><details><summary class="button">مدیریت حساب</summary><div style="padding:12px;display:grid;gap:10px;max-width:440px">
        <form method="post"><?php wp_nonce_field(self::ACTION);?><input type="hidden" name="woogit_action" value="edit"><input type="hidden" name="account_id" value="<?php echo esc_attr($r['id']);?>"><label>ایمیل تماس<br><input type="email" name="email" value="<?php echo esc_attr($r['email']??'');?>" style="width:100%"></label><label>وضعیت<br><select name="status" style="width:100%"><option value="active" <?php selected($r['status'],'active');?>>active</option><option value="suspended" <?php selected($r['status'],'suspended');?>>suspended</option><option value="disabled" <?php selected($r['status'],'disabled');?>>disabled</option></select></label><button class="button button-primary">ذخیره ویرایش</button></form>
        <?php if($r['site_id']):?><form method="post"><?php wp_nonce_field(self::ACTION);?><input type="hidden" name="woogit_action" value="activate"><input type="hidden" name="account_id" value="<?php echo esc_attr($r['id']);?>"><input type="hidden" name="site_id" value="<?php echo esc_attr($r['site_id']);?>"><label>بسته<br><select name="product_id" required style="width:100%"><option value="">انتخاب...</option><?php foreach($plans as $p):?><option value="<?php echo esc_attr($p['id']);?>"><?php echo esc_html($p['name'].' — '.$p['days'].' روز');?></option><?php endforeach;?></select></label><label>روز اضافه اختیاری<br><input type="number" name="extra_days" min="0" max="3650"></label><button class="button button-primary">فعال‌سازی دستی بسته</button></form>
        <form method="post"><?php wp_nonce_field(self::ACTION);?><input type="hidden" name="woogit_action" value="deactivate"><input type="hidden" name="account_id" value="<?php echo esc_attr($r['id']);?>"><input type="hidden" name="site_id" value="<?php echo esc_attr($r['site_id']);?>"><button class="button">لغو دسترسی بسته</button></form><?php endif;?>
        <form method="post"><?php wp_nonce_field(self::ACTION);?><input type="hidden" name="woogit_action" value="logout"><input type="hidden" name="account_id" value="<?php echo esc_attr($r['id']);?>"><button class="button">خروج اجباری همه Sessionها</button></form>
        <form method="post"><?php wp_nonce_field(self::ACTION);?><input type="hidden" name="woogit_action" value="repair"><input type="hidden" name="account_id" value="<?php echo esc_attr($r['id']);?>"><button class="button">تعمیر Identity</button></form>
        <form method="post"><?php wp_nonce_field(self::ACTION);?><input type="hidden" name="woogit_action" value="trial"><input type="hidden" name="account_id" value="<?php echo esc_attr($r['id']);?>"><button class="button">بازنشانی Trial</button></form>
        <form method="post" onsubmit="return confirm('حذف کامل حساب، سایت، دسترسی و Identity انجام شود؟');"><?php wp_nonce_field(self::ACTION);?><input type="hidden" name="woogit_action" value="delete"><input type="hidden" name="account_id" value="<?php echo esc_attr($r['id']);?>"><button class="button button-link-delete">حذف کامل حساب</button></form>
        </div></details></td></tr><?php endforeach;endif;?></tbody></table>
        <h2>امکانات مدیریتی</h2><p>جستجو، ویرایش ایمیل، تغییر وضعیت، فعال‌سازی بسته، تمدید دستی، لغو دسترسی، خروج اجباری Session، تعمیر Identity، بازنشانی Trial، حذف کامل حساب، مشاهده سایت، مشاهده وضعیت Entitlement، تاریخ شروع/انقضا، Capabilityها و مشاهده زمان ایجاد/به‌روزرسانی.</p></div><?php
    }
    private function action():?array{
        if(($_SERVER['REQUEST_METHOD']??'')!=='POST'||empty($_POST['woogit_action']))return null;if(!current_user_can('manage_options'))return['error','دسترسی غیرمجاز.'];check_admin_referer(self::ACTION);$act=sanitize_key((string)$_POST['woogit_action']);$id=absint($_POST['account_id']??0);if(!$id)return['error','Account نامعتبر است.'];global $wpdb;$a=$wpdb->prefix.'woogit_accounts';$s=$wpdb->prefix.'woogit_sites';$e=$wpdb->prefix.'woogit_entitlements';$ws=$wpdb->prefix.'woogit_web_sessions';$ss=$wpdb->prefix.'woogit_sessions';if(!$wpdb->get_var($wpdb->prepare("SELECT id FROM {$a} WHERE id=%d",$id)))return['error','Account پیدا نشد.'];$now=gmdate('Y-m-d H:i:s');
        if($act==='edit'){$email=sanitize_email(wp_unslash((string)($_POST['email']??'')));$status=sanitize_key((string)($_POST['status']??''));if($email!==''&&!is_email($email)||!in_array($status,['active','suspended','disabled'],true))return['error','اطلاعات نامعتبر است.'];$ok=false!==$wpdb->update($a,['email'=>$email!==''?$email:null,'status'=>$status,'updated_at'=>$now],['id'=>$id],['%s','%s','%s'],['%d']);if($status!=='active'){$wpdb->query($wpdb->prepare("UPDATE {$ws} SET revoked_at=%s WHERE account_id=%d AND revoked_at IS NULL",$now,$id));$wpdb->query($wpdb->prepare("UPDATE {$ss} SET revoked_at=%s WHERE account_id=%d AND revoked_at IS NULL",$now,$id));}return[$ok?'success':'error',$ok?'حساب ویرایش شد.':'ویرایش ذخیره نشد.'];}
        if($act==='logout'){$wpdb->query($wpdb->prepare("UPDATE {$ws} SET revoked_at=%s WHERE account_id=%d AND revoked_at IS NULL",$now,$id));$wpdb->query($wpdb->prepare("UPDATE {$ss} SET revoked_at=%s WHERE account_id=%d AND revoked_at IS NULL",$now,$id));return['success','همه Sessionها لغو شدند.'];}
        if($act==='repair')return(new AccountService())->ensureIdentity($id)?['success','Identity بررسی/تعمیر شد.']:['error','تعمیر Identity انجام نشد.'];
        if($act==='trial'){$ok=false!==$wpdb->update($a,['trial_used_at'=>null,'updated_at'=>$now],['id'=>$id],['%s','%s'],['%d']);return[$ok?'success':'error',$ok?'Trial بازنشانی شد.':'Trial بازنشانی نشد.'];}
        if($act==='deactivate'){$site=absint($_POST['site_id']??0);if(!$site)return['error','Site نامعتبر است.'];$ok=false!==$wpdb->update($e,['status'=>'inactive','updated_at'=>$now],['account_id'=>$id,'site_id'=>$site],['%s','%s'],['%d','%d']);(new WebSessionService())->revokeAllForAccount($id);return[$ok?'success':'error',$ok?'دسترسی بسته لغو شد.':'Entitlement پیدا نشد.'];}
        if($act==='activate')return$this->activate($id,absint($_POST['site_id']??0),absint($_POST['product_id']??0),absint($_POST['extra_days']??0));
        if($act==='delete'){$uid=(int)$wpdb->get_var($wpdb->prepare("SELECT wp_user_id FROM {$a} WHERE id=%d",$id));foreach([$ws,$ss,$e,$wpdb->prefix.'woogit_idempotency',$wpdb->prefix.'woogit_operations',$s,$a] as $table)$wpdb->delete($table,['account_id'=>$id],['%d']);if($uid>0)wp_delete_user($uid);return['success','حساب، سایت، Entitlement و Sessionهای آن حذف شد؛ سفارش‌های WooCommerce حفظ شدند.'];}
        return['error','عملیات ناشناخته است.'];
    }
    private function activate(int $id,int $site,int $productId,int $extra):array{
        if(!$site||!$productId)return['error','سایت یا بسته انتخاب نشده است.'];if(!function_exists('wc_get_product'))return['error','WooCommerce در دسترس نیست.'];$p=wc_get_product($productId);if(!$p||$p->get_status()!=='publish')return['error','بسته معتبر نیست.'];$enabled=get_post_meta($productId,'_woogit_plan_enabled',true);if($enabled!==''&&$enabled!=='yes')return['error','این محصول WooGit Plan فعال نیست.'];$period=(string)$p->get_meta('_subscription_period');$interval=max(1,(int)($p->get_meta('_subscription_period_interval')?:1));$base=$this->days($period,$interval);$days=$base+max(0,min(3650,$extra));if($days<=0)return['error','مدت بسته قابل تشخیص نیست.'];global $wpdb;$t=$wpdb->prefix.'woogit_entitlements';$now=time();$data=['status'=>'active','starts_at'=>gmdate('Y-m-d H:i:s',$now),'expires_at'=>gmdate('Y-m-d H:i:s',$now+$days*DAY_IN_SECONDS),'capabilities'=>wp_json_encode(['commerce']),'updated_at'=>gmdate('Y-m-d H:i:s',$now)];$old=$wpdb->get_var($wpdb->prepare("SELECT id FROM {$t} WHERE account_id=%d AND site_id=%d LIMIT 1",$id,$site));if($old)$ok=false!==$wpdb->update($t,$data,['id'=>(int)$old],['%s','%s','%s','%s','%s'],['%d']);else{$data['account_id']=$id;$data['site_id']=$site;$data['created_at']=gmdate('Y-m-d H:i:s',$now);$ok=false!==$wpdb->insert($t,$data,['%s','%s','%s','%s','%s','%d','%d','%s']);}if(!$ok)return['error','فعال‌سازی بسته ذخیره نشد.'];(new WebSessionService())->revokeAllForAccount($id);return['success','بسته «'.$p->get_name().'» برای حساب فعال شد.'];
    }
    private function plans():array{if(!function_exists('wc_get_products'))return[];$out=[];foreach((array)wc_get_products(['status'=>'publish','limit'=>-1]) as $p){if(!$p||!$p->is_purchasable())continue;$enabled=get_post_meta((int)$p->get_id(),'_woogit_plan_enabled',true);if($enabled!==''&&$enabled!=='yes')continue;$days=$this->days((string)$p->get_meta('_subscription_period'),max(1,(int)($p->get_meta('_subscription_period_interval')?:1)));if($days<=0)continue;$out[]=['id'=>(int)$p->get_id(),'name'=>(string)$p->get_name(),'days'=>$days];}return$out;}
    private function days(string $period,int $interval):int{$m=['day'=>1,'week'=>7,'month'=>30,'year'=>365];return isset($m[$period])?$m[$period]*$interval:0;}
}
