<?php
namespace WooGit\Backend;

defined('ABSPATH') || exit;

final class RestController
{
    private SessionService $sessions; private AccountService $accounts; private SiteService $sites; private EntitlementService $entitlements; private IdempotencyService $idempotency; private OperationService $operations; private ProxyPolicy $policy; private WooCommerceProxy $proxy; private RateLimitService $rateLimits; private VersionGate $versionGate;
    private const MAX_BODY_BYTES=5242880; private const MAX_MEDIA_BYTES=10485760;
    public function __construct(){ $this->sessions=new SessionService();$this->accounts=new AccountService();$this->sites=new SiteService();$this->entitlements=new EntitlementService();$this->idempotency=new IdempotencyService();$this->operations=new OperationService();$this->policy=new ProxyPolicy();$this->proxy=new WooCommerceProxy();$this->rateLimits=new RateLimitService();$this->versionGate=new VersionGate(); }
    public function register(): void{register_rest_route('woogit/v1','/sites/verify',['methods'=>'POST','permission_callback'=>'__return_true','callback'=>[$this,'verifySite']]);register_rest_route('woogit/v1','/sessions/revoke',['methods'=>'POST','permission_callback'=>'__return_true','callback'=>[$this,'revokeSession']]);register_rest_route('woogit/v1','/operations/(?P<operation_id>[A-Za-z0-9_-]+)',['methods'=>'GET','permission_callback'=>'__return_true','callback'=>[$this,'getOperation']]);register_rest_route('woogit/v1','/forward',['methods'=>['GET','POST','PUT','PATCH','DELETE'],'permission_callback'=>'__return_true','callback'=>[$this,'forward']]);}

    public function verifySite(\WP_REST_Request $request): \WP_REST_Response
    {
        $gate=$this->versionResponse($request);if($gate instanceof \WP_REST_Response)return $gate;$limit=$this->rateLimits->check('verify',$this->clientIp(),10,60);if(!$limit['allowed'])return $this->rateLimited($limit['retry_after']);
        $key=trim((string)$request->get_header('Idempotency-Key'));if($key===''||strlen($key)>190||!preg_match('/^[A-Za-z0-9._:-]{1,190}$/',$key))return new \WP_REST_Response(['code'=>'invalid_idempotency_key'],400);
        $rawBody=(string)$request->get_body();$fingerprint=$this->idempotency->fingerprint('POST','/sites/verify',$request->get_query_params(),$rawBody);$lookup=$this->idempotency->lookupVerify($key,$fingerprint);
        if($lookup['state']==='conflict')return new \WP_REST_Response(['code'=>'idempotency_conflict'],409);
        if($lookup['state']==='completed')return new \WP_REST_Response($lookup['body'],$lookup['status']);
        if($lookup['state']==='unknown')return new \WP_REST_Response(['code'=>'operation_status_unknown','operation_id'=>$lookup['operation_id'],'status'=>'unknown','retryable'=>false,'requires_reconciliation'=>true],409);
        $operationId='';
        if($lookup['state']==='pending'){
            $operation=$this->operations->getByOperationId($lookup['operation_id']);
            if(!$operation)return new \WP_REST_Response(['code'=>'operation_status_unknown','operation_id'=>$lookup['operation_id'],'status'=>'unknown','retryable'=>false,'requires_reconciliation'=>true],409);
            if((string)$operation['status']==='unknown'){$this->idempotency->markVerifyUnknown($key);return new \WP_REST_Response(['code'=>'operation_status_unknown','operation_id'=>$lookup['operation_id'],'status'=>'unknown','retryable'=>false,'requires_reconciliation'=>true],409);}
            if((int)$operation['account_id']<=0||(int)$operation['site_id']<=0)return new \WP_REST_Response(['code'=>'operation_in_progress','operation_id'=>$lookup['operation_id'],'status'=>'pending','retryable'=>true],202);
            return $this->finishVerifiedContext($key,$lookup['operation_id'],(int)$operation['account_id'],(int)$operation['site_id']);
        }
        $candidate=$this->operations->create(0,0,$key,$fingerprint,'verify','/sites/verify','POST');if($candidate===null){$retry=$this->idempotency->lookupVerify($key,$fingerprint);if($retry['state']==='completed')return new \WP_REST_Response($retry['body'],$retry['status']);if($retry['state']==='pending')return new \WP_REST_Response(['code'=>'operation_in_progress','operation_id'=>$retry['operation_id'],'status'=>'pending','retryable'=>true],202);if($retry['state']==='conflict')return new \WP_REST_Response(['code'=>'idempotency_conflict'],409);return new \WP_REST_Response(['code'=>'operation_unavailable'],500);}$operationId=$candidate['operation_id'];$claim=$this->idempotency->claimVerify($key,$fingerprint,$operationId);if($claim['state']!=='claimed'){ $this->operations->deletePending(0,0,$operationId);if($claim['state']==='completed')return new \WP_REST_Response($claim['body'],$claim['status']);if($claim['state']==='pending')return new \WP_REST_Response(['code'=>'operation_in_progress','operation_id'=>$claim['operation_id'],'status'=>'pending','retryable'=>true],202);if($claim['state']==='conflict')return new \WP_REST_Response(['code'=>'idempotency_conflict'],409);return new \WP_REST_Response(['code'=>'operation_unavailable'],500);}

        $input=$request->get_json_params();$input=is_array($input)?$input:[];$url=trim((string)($input['url']??''));$email=sanitize_email((string)($input['email']??''));foreach(['wordpress_username','wordpress_application_password','consumer_key','consumer_secret'] as $field)if(!isset($input[$field])||!is_string($input[$field])||$input[$field]==='')return $this->verifyFailure($key,$operationId,'missing_customer_credentials',400);
        $base=$this->policy->resolveSiteUrl($url);if($base===null||($email!==''&&!is_email($email)))return $this->verifyFailure($key,$operationId,'invalid_site_or_email',400);
        $verification=$this->proxy->verify($base,$input['wordpress_username'],$input['wordpress_application_password'],$input['consumer_key'],$input['consumer_secret']);if(!$verification['ok'])return $this->verifyFailure($key,$operationId,'site_verification_failed',502,$verification['reason']);
        $existingSite=$this->sites->findByHost((string)wp_parse_url($base,PHP_URL_HOST));
        if($existingSite){if($existingSite['status']!=='active')return $this->verifyFailure($key,$operationId,'site_unavailable',409);$account=$this->accounts->get((int)$existingSite['account_id']);if(!$account)return $this->verifyFailure($key,$operationId,'account_unavailable',409);if($email!==''&&!$this->accounts->updateContactEmail((int)$account['id'],$email))return $this->verifyFailure($key,$operationId,'contact_email_unavailable',500);$site=$existingSite;}
        else{$account=$this->accounts->create($email);if(!$account)return $this->verifyFailure($key,$operationId,'account_creation_failed',500);$site=$this->sites->findOrCreate((int)$account['id'],$base);if(!$site){$this->accounts->deleteIfEmpty((int)$account['id']);return $this->verifyFailure($key,$operationId,'site_creation_failed',409);}}
        if(!$this->operations->bindContext($operationId,(int)$account['id'],(int)$site['id']))return $this->verifyFailure($key,$operationId,'operation_persistence_failed',503);
        return $this->finishVerifiedContext($key,$operationId,(int)$account['id'],(int)$site['id']);
    }

    private function finishVerifiedContext(string $key,string $operationId,int $accountId,int $siteId): \WP_REST_Response
    {
        if(!$this->entitlements->grantTrial($accountId,$siteId))return $this->verifyFailure($key,$operationId,'entitlement_unavailable',500,$accountId,$siteId);
        $accessEnabled=$this->entitlements->isAllowed($accountId,$siteId,'commerce');$expires=$this->entitlements->getExpiresAt($accountId,$siteId);$token=$accessEnabled?$this->sessions->issueOperational($accountId,$siteId,(int)$expires):$this->sessions->issueBilling($accountId,$siteId);if(!$token)return $this->verifyFailure($key,$operationId,'session_creation_failed',500,$accountId,$siteId);
        $scope=$accessEnabled?SessionService::SCOPE_OPERATIONAL:SessionService::SCOPE_BILLING;$body=['account_id'=>$accountId,'site_id'=>$siteId,'session'=>$token,'scope'=>$scope,'access_enabled'=>$accessEnabled,'billing_required'=>!$accessEnabled];
        if(!$this->operations->update($accountId,$siteId,$operationId,'succeeded',200,['verify_completed'=>true])){ $this->idempotency->markVerifyUnknown($key);$this->operations->markUnknown($accountId,$siteId,$operationId);return new \WP_REST_Response(['code'=>'operation_persistence_failed','operation_id'=>$operationId,'status'=>'unknown','retryable'=>false,'requires_reconciliation'=>true],503); }
        if(!$this->idempotency->completeVerify($key,200,$body)){ $this->operations->markUnknown($accountId,$siteId,$operationId);$this->idempotency->markVerifyUnknown($key);return new \WP_REST_Response(['code'=>'operation_persistence_failed','operation_id'=>$operationId,'status'=>'unknown','retryable'=>false,'requires_reconciliation'=>true],503); }
        return new \WP_REST_Response($body,200);
    }

    private function verifyFailure(string $key,string $operationId,string $code,int $status,string $reason='',int $accountId=0,int $siteId=0): \WP_REST_Response
    {
        $body=['code'=>$code];if($reason!=='')$body['reason']=$reason;if($accountId>0&&$siteId>0)$this->operations->update($accountId,$siteId,$operationId,'failed',$status,$body);else{$operation=$this->operations->getByOperationId($operationId);if($operation&&((int)$operation['account_id']>0||$accountId>0))$this->operations->update($accountId>0?$accountId:(int)$operation['account_id'],$siteId>0?$siteId:(int)$operation['site_id'],'failed',$status,$body);}
        if(!$this->idempotency->completeVerify($key,$status,$body))$this->idempotency->markVerifyUnknown($key);return new \WP_REST_Response($body,$status);
    }

    public function revokeSession(\WP_REST_Request $request): \WP_REST_Response{$gate=$this->versionResponse($request);if($gate instanceof \WP_REST_Response)return $gate;return new \WP_REST_Response(['revoked'=>$this->sessions->revoke((string)$request->get_header('X-WooGit-Session'))],200);}
    public function getOperation(\WP_REST_Request $request): \WP_REST_Response{$gate=$this->versionResponse($request);if($gate instanceof \WP_REST_Response)return $gate;$session=$this->authenticateContext($request);if($session instanceof \WP_REST_Response)return $session;$limit=$this->rateLimits->check('operation',(string)$session['account_id'].':'.(string)$session['site_id'],120,60);if(!$limit['allowed'])return $this->rateLimited($limit['retry_after']);$operationId=sanitize_text_field((string)$request['operation_id']);$operation=$this->operations->getForAccount((int)$session['account_id'],(int)$session['site_id'],$operationId);if(!$operation)return new \WP_REST_Response(['code'=>'operation_not_found'],404);return new \WP_REST_Response(['operation_id'=>$operation['operation_id'],'status'=>$operation['status'],'path'=>$operation['operation_path'],'method'=>$operation['method'],'upstream_status'=>$operation['upstream_status'],'response'=>$operation['response_body'],'created_at'=>$operation['created_at'],'updated_at'=>$operation['updated_at'],'expires_at'=>$operation['expires_at']],200);}
    public function forward(\WP_REST_Request $request): \WP_REST_Response
    {
        $gate=$this->versionResponse($request);if($gate instanceof \WP_REST_Response)return $gate;$session=$this->authenticateContext($request);if($session instanceof \WP_REST_Response)return $session;$limit=$this->rateLimits->check('forward',(string)$session['account_id'].':'.(string)$session['site_id'],120,60);if(!$limit['allowed'])return $this->rateLimited($limit['retry_after']);$path=$this->policy->validatePath((string)$request->get_param('path'));if($path===null)return new \WP_REST_Response(['code'=>'operation_not_allowed'],404);$method=strtoupper($request->get_method());$key=trim((string)$request->get_header('Idempotency-Key'));if($key!==''&&(strlen($key)>190||!preg_match('/^[A-Za-z0-9._:-]{1,190}$/',$key)))return new \WP_REST_Response(['code'=>'invalid_idempotency_key'],400);if(!$this->policy->validateMethod($method,$key!==''))return new \WP_REST_Response(['code'=>'invalid_mutation_request'],400);$base=$this->policy->resolveSiteUrl($session['site']['canonical_url']);if($base===null)return new \WP_REST_Response(['code'=>'invalid_site_identity'],403);$credentials=$this->credentials($request,$path);if($credentials===null)return new \WP_REST_Response(['code'=>'missing_customer_credentials'],400);$query=$request->get_query_params();unset($query['path']);$rawBody=(string)$request->get_body();$contentType=(string)$request->get_header('content-type');$maxBody=str_starts_with($path,'/wp-json/wp/v2/media')?self::MAX_MEDIA_BYTES:self::MAX_BODY_BYTES;if(strlen($rawBody)>$maxBody)return new \WP_REST_Response(['code'=>'request_body_too_large','max_bytes'=>$maxBody],413);$fingerprint=$this->idempotency->fingerprint($method,$path,$query,$rawBody);$operationId='';
        if($key!==''){$candidate=$this->operations->create((int)$session['account_id'],(int)$session['site_id'],$key,$fingerprint,'proxy',$path,$method);if($candidate===null){$existing=$this->idempotency->lookup((int)$session['account_id'],(int)$session['site_id'],$key,$fingerprint);if($existing['state']==='conflict')return new \WP_REST_Response(['code'=>'idempotency_conflict'],409);if($existing['state']==='completed')return new \WP_REST_Response($existing['body'],$existing['status']);if($existing['state']==='pending')return new \WP_REST_Response(['code'=>'operation_in_progress','operation_id'=>$existing['operation_id'],'status'=>'pending','retryable'=>true],202);if($existing['state']==='unknown')return new \WP_REST_Response(['code'=>'operation_status_unknown','operation_id'=>$existing['operation_id'],'status'=>'unknown','retryable'=>false,'requires_reconciliation'=>true],409);return new \WP_REST_Response(['code'=>'operation_unavailable'],500);} $operationId=$candidate['operation_id'];$claim=$this->idempotency->claim((int)$session['account_id'],(int)$session['site_id'],$key,$fingerprint,$operationId);if($claim['state']!=='claimed'){$this->operations->deletePending((int)$session['account_id'],(int)$session['site_id'],$operationId);if($claim['state']==='conflict')return new \WP_REST_Response(['code'=>'idempotency_conflict'],409);if($claim['state']==='completed')return new \WP_REST_Response($claim['body'],$claim['status']);if($claim['state']==='pending')return new \WP_REST_Response(['code'=>'operation_in_progress','operation_id'=>$claim['operation_id'],'status'=>'pending','retryable'=>true],202);if($claim['state']==='unknown')return new \WP_REST_Response(['code'=>'operation_status_unknown','operation_id'=>$claim['operation_id'],'status'=>'unknown','retryable'=>false,'requires_reconciliation'=>true],409);return new \WP_REST_Response(['code'=>'operation_unavailable'],500);}}
        $result=$this->proxy->forward($base,$path,$method,$credentials['wordpress_username'],$credentials['wordpress_application_password'],$credentials['consumer_key'],$credentials['consumer_secret'],$query,$rawBody,$contentType);$status=(int)$result['status'];$rawResponse=(string)$result['body'];$decoded=json_decode($rawResponse,true);$responseBody=json_last_error()===JSON_ERROR_NONE?$decoded:$rawResponse;$idempotentBody=is_array($decoded)?$decoded:['raw'=>$rawResponse];
        if($key!==''){if(!empty($result['timeout'])){$this->idempotency->markUnknown((int)$session['account_id'],(int)$session['site_id'],$key);$this->operations->markUnknown((int)$session['account_id'],(int)$session['site_id'],$operationId);return new \WP_REST_Response(['code'=>'upstream_timeout','operation_id'=>$operationId,'status'=>'unknown','retryable'=>false,'requires_reconciliation'=>true],504);}$operationStatus=$status>=200&&$status<300?'succeeded':'failed';$operationSaved=$this->operations->update((int)$session['account_id'],(int)$session['site_id'],$operationId,$operationStatus,$status,$idempotentBody);$idempotencySaved=$this->idempotency->complete((int)$session['account_id'],(int)$session['site_id'],$key,$status,$idempotentBody);if(!$operationSaved||!$idempotencySaved){$this->idempotency->markUnknown((int)$session['account_id'],(int)$session['site_id'],$key);$this->operations->markUnknown((int)$session['account_id'],(int)$session['site_id'],$operationId);return new \WP_REST_Response(['code'=>'operation_persistence_failed','operation_id'=>$operationId,'status'=>'unknown','retryable'=>false,'requires_reconciliation'=>true],503);}}
        $response=new \WP_REST_Response($responseBody,$status);foreach($result['headers'] as $header=>$value)$response->header($header,$value);return $response;
    }
    private function authenticateContext(\WP_REST_Request $request): array|\WP_REST_Response{$session=$this->sessions->authenticate((string)$request->get_header('X-WooGit-Session'));if($session===null)return new \WP_REST_Response(['code'=>'invalid_session'],401);if(($session['scope']??'')!==SessionService::SCOPE_OPERATIONAL)return new \WP_REST_Response(['code'=>'insufficient_session_scope'],403);$account=$this->accounts->get((int)$session['account_id']);if(!$account)return new \WP_REST_Response(['code'=>'account_inactive'],403);$site=$this->sites->getOwned((int)$session['account_id'],(int)$session['site_id']);if(!$site)return new \WP_REST_Response(['code'=>'site_not_owned'],403);if(!$this->entitlements->isAllowed((int)$session['account_id'],(int)$session['site_id'],'commerce'))return new \WP_REST_Response(['code'=>'not_entitled'],403);$expires=$this->entitlements->getExpiresAt((int)$session['account_id'],(int)$session['site_id']);if($expires!==null)$this->sessions->reconcileOperational((int)$session['account_id'],(int)$session['site_id'],$expires);$session['site']=$site;return $session;}
    private function credentials(\WP_REST_Request $request,string $path): ?array{$isWordPressMedia=$path==='/wp-json/wp/v2/media'||str_starts_with($path,'/wp-json/wp/v2/media/');$headers=$isWordPressMedia?['X-WooGit-Wordpress-Username'=>'wordpress_username','X-WooGit-Wordpress-Application-Password'=>'wordpress_application_password']:['X-WooGit-Consumer-Key'=>'consumer_key','X-WooGit-Consumer-Secret'=>'consumer_secret'];$result=['wordpress_username'=>'','wordpress_application_password'=>'','consumer_key'=>'','consumer_secret'=>''];foreach($headers as $header=>$field){$value=(string)$request->get_header($header);if($value==='')return null;$result[$field]=$value;}return $result;}
    private function versionResponse(\WP_REST_Request $request): ?\WP_REST_Response{$result=$this->versionGate->check((string)$request->get_header('X-WooGit-App-Version'));if($result['allowed'])return null;$policy=$result['policy'];$status=$result['code']==='APP_VERSION_DEPRECATED'?426:400;return new \WP_REST_Response(['code'=>$result['code'],'message'=>$result['code']==='APP_VERSION_DEPRECATED'?'این نسخه از WooGit دیگر پشتیبانی نمی‌شود.':'نسخه Client نامعتبر است.','minimum_supported_version'=>$policy['minimum_supported_version'],'latest_version'=>$policy['latest_version'],'recommended_version'=>$policy['recommended_version'],'update_required'=>$result['code']==='APP_VERSION_DEPRECATED','retryable'=>false],$status);}
    private function rateLimited(int $retryAfter): \WP_REST_Response{$response=new \WP_REST_Response(['code'=>'RATE_LIMITED','retry_after'=>$retryAfter,'retryable'=>true],429);$response->header('Retry-After',(string)$retryAfter);return $response;}
    private function clientIp(): string{$ip=isset($_SERVER['REMOTE_ADDR'])?trim((string)$_SERVER['REMOTE_ADDR']):'';return filter_var($ip,FILTER_VALIDATE_IP)?$ip:'unknown';}
}
