<?php
namespace WooGit\Backend;

defined('ABSPATH') || exit;

final class WebAuthController
{
    private AccountService $accounts; private SiteService $sites; private SessionService $sessions; private WebSessionService $webSessions; private ProxyPolicy $policy; private RateLimitService $rateLimits; private BillingService $billing; private RequirementService $requirements; private IdentityService $identity; private WooCommerceProxy $proxy; private IdempotencyService $idempotency; private OperationService $operations; private EntitlementService $entitlements;
    public function __construct(){ $this->accounts=new AccountService();$this->sites=new SiteService();$this->sessions=new SessionService();$this->webSessions=new WebSessionService();$this->policy=new ProxyPolicy();$this->rateLimits=new RateLimitService();$this->billing=new BillingService();$this->requirements=new RequirementService();$this->identity=new IdentityService();$this->proxy=new WooCommerceProxy();$this->idempotency=new IdempotencyService();$this->operations=new OperationService();$this->entitlements=new EntitlementService(); }
    public function register(): void{register_rest_route('woogit/v1','/account/requirements',['methods'=>'GET','permission_callback'=>'__return_true','callback'=>[$this,'requirements']]);register_rest_route('woogit/v1','/account/web-bootstrap',['methods'=>'POST','permission_callback'=>'__return_true','callback'=>[$this,'webBootstrap']]);register_rest_route('woogit/v1','/account/setup-web-credentials',['methods'=>'POST','permission_callback'=>'__return_true','callback'=>[$this,'setupWebCredentials']]);register_rest_route('woogit/v1','/web/login',['methods'=>'POST','permission_callback'=>'__return_true','callback'=>[$this,'login']]);register_rest_route('woogit/v1','/web/logout',['methods'=>'POST','permission_callback'=>'__return_true','callback'=>[$this,'logout']]);register_rest_route('woogit/v1','/web/me',['methods'=>'GET','permission_callback'=>'__return_true','callback'=>[$this,'me']]);register_rest_route('woogit/v1','/web/account/contact-email',['methods'=>'POST','permission_callback'=>'__return_true','callback'=>[$this,'updateContactEmail']]);register_rest_route('woogit/v1','/web/account/password',['methods'=>'POST','permission_callback'=>'__return_true','callback'=>[$this,'changePassword']]);register_rest_route('woogit/v1','/web/billing/history',['methods'=>'GET','permission_callback'=>'__return_true','callback'=>[$this,'paymentHistory']]);}
    public function requirements(\WP_REST_Request $request): \WP_REST_Response{$context=$this->apiContext($request);if($context instanceof \WP_REST_Response)return $context;$account=$this->accounts->get((int)$context['account_id']);if(!$account)return new \WP_REST_Response(['code'=>'account_inactive'],403);return new \WP_REST_Response(['account_id'=>(int)$context['account_id'],'site_id'=>(int)$context['site_id'],'requirements'=>$this->requirements->build($account)],200);}
    public function webBootstrap(\WP_REST_Request $request): \WP_REST_Response
    {
        $limit=$this->rateLimits->check('web_bootstrap_ip',$this->clientIp(),5,60);if(!$limit['allowed'])return $this->rateLimited($limit['retry_after']);
        $key=trim((string)$request->get_header('Idempotency-Key'));if($key===''||strlen($key)>190||!preg_match('/^[A-Za-z0-9._:-]{1,190}$/',$key))return new \WP_REST_Response(['code'=>'invalid_idempotency_key'],400);
        $rawBody=(string)$request->get_body();$fingerprint=$this->idempotency->fingerprint('POST','/account/web-bootstrap',$request->get_query_params(),$rawBody);$lookup=$this->idempotency->lookupVerify($key,$fingerprint);
        if($lookup['state']==='conflict')return new \WP_REST_Response(['code'=>'idempotency_conflict'],409);if($lookup['state']==='completed')return new \WP_REST_Response($lookup['body'],$lookup['status']);if($lookup['state']==='unknown')return new \WP_REST_Response(['code'=>'operation_status_unknown','operation_id'=>$lookup['operation_id'],'status'=>'unknown','retryable'=>false,'requires_reconciliation'=>true],409);if($lookup['state']==='pending')return new \WP_REST_Response(['code'=>'operation_in_progress','operation_id'=>$lookup['operation_id'],'status'=>'pending','retryable'=>true],202);
        $candidate=$this->operations->create(0,0,$key,$fingerprint,'web_bootstrap','/account/web-bootstrap','POST');if($candidate===null){$retry=$this->idempotency->lookupVerify($key,$fingerprint);if($retry['state']==='completed')return new \WP_REST_Response($retry['body'],$retry['status']);if($retry['state']==='pending')return new \WP_REST_Response(['code'=>'operation_in_progress','operation_id'=>$retry['operation_id'],'status'=>'pending','retryable'=>true],202);if($retry['state']==='conflict')return new \WP_REST_Response(['code'=>'idempotency_conflict'],409);return new \WP_REST_Response(['code'=>'operation_unavailable'],500);}
        $operationId=$candidate['operation_id'];$claim=$this->idempotency->claimVerify($key,$fingerprint,$operationId);if($claim['state']!=='claimed'){ $this->operations->deletePending(0,0,$operationId);if($claim['state']==='completed')return new \WP_REST_Response($claim['body'],$claim['status']);if($claim['state']==='pending')return new \WP_REST_Response(['code'=>'operation_in_progress','operation_id'=>$claim['operation_id'],'status'=>'pending','retryable'=>true],202);if($claim['state']==='conflict')return new \WP_REST_Response(['code'=>'idempotency_conflict'],409);return new \WP_REST_Response(['code'=>'operation_unavailable'],500);}
        $input=$request->get_json_params();$input=is_array($input)?$input:[];$url=trim((string)($input['site_url']??''));$password=(string)($input['web_password']??'');$confirmation=(string)($input['web_password_confirmation']??'');$required=['wp_username','wp_application_password','consumer_key','consumer_secret'];foreach($required as $field)if(!isset($input[$field])||!is_string($input[$field])||$input[$field]==='')return $this->webBootstrapFailure($key,$operationId,'missing_customer_credentials',400);if(strlen($password)<12||strlen($password)>256)return $this->webBootstrapFailure($key,$operationId,'invalid_web_password',400);if(!hash_equals($password,$confirmation))return $this->webBootstrapFailure($key,$operationId,'password_confirmation_mismatch',400);
        $base=$this->policy->resolveSiteUrl($url);if($base===null)return $this->webBootstrapFailure($key,$operationId,'invalid_site_url',400);
        $verification=$this->proxy->verify($base,$input['wp_username'],$input['wp_application_password'],$input['consumer_key'],$input['consumer_secret']);if(!$verification['ok'])return $this->webBootstrapFailure($key,$operationId,'site_verification_failed',502,$verification['reason']);
        $host=strtolower(rtrim((string)wp_parse_url($base,PHP_URL_HOST),'.'));$existingSite=$this->sites->findByHost($host);$account=null;$site=null;
        if($existingSite){if($existingSite['status']!=='active')return $this->webBootstrapFailure($key,$operationId,'site_unavailable',409);$account=$this->accounts->get((int)$existingSite['account_id']);if(!$account)return $this->webBootstrapFailure($key,$operationId,'account_unavailable',409);$site=$existingSite;if($this->accounts->hasWebPassword((int)$account['id']))return $this->webBootstrapFailure($key,$operationId,'web_credentials_already_configured',409);}
        else{$account=$this->accounts->create();if(!$account)return $this->webBootstrapFailure($key,$operationId,'account_creation_failed',500);$site=$this->sites->findOrCreate((int)$account['id'],$base);if(!$site){$this->accounts->deleteIfEmpty((int)$account['id']);return $this->webBootstrapFailure($key,$operationId,'site_creation_failed',409);}}
        $accountId=(int)$account['id'];$siteId=(int)$site['id'];if(!$this->accounts->setWebPassword($accountId,$password))return $this->webBootstrapFailure($key,$operationId,'web_password_unavailable',500,$accountId,$siteId);if(!$this->entitlements->grantTrial($accountId,$siteId))return $this->webBootstrapFailure($key,$operationId,'entitlement_unavailable',500,'',$accountId,$siteId);if(!$this->operations->bindContext($operationId,$accountId,$siteId))return $this->webBootstrapFailure($key,$operationId,'operation_persistence_failed',503,'',$accountId,$siteId);
        $session=$this->webSessions->issue($accountId,$siteId);if(!$session)return $this->webBootstrapFailure($key,$operationId,'web_session_creation_failed',500,'',$accountId,$siteId);$body=['session'=>$session['token'],'expires_at'=>gmdate('Y-m-d H:i:s',$session['expires_at']),'account_id'=>$accountId,'site_id'=>$siteId];if(!$this->operations->update($accountId,$siteId,$operationId,'succeeded',200,$body)||!$this->idempotency->completeVerify($key,200,$body)){ $this->operations->markUnknown($accountId,$siteId,$operationId);$this->idempotency->markVerifyUnknown($key);return new \WP_REST_Response(['code'=>'operation_persistence_failed','operation_id'=>$operationId,'status'=>'unknown','retryable'=>false,'requires_reconciliation'=>true],503); }return new \WP_REST_Response($body,200);
    }
    public function setupWebCredentials(\WP_REST_Request $request): \WP_REST_Response
    {
        $context=$this->apiContext($request);if($context instanceof \WP_REST_Response)return $context;$accountId=(int)$context['account_id'];$limit=$this->rateLimits->check('web_setup',(string)$accountId.':'.(string)$context['site_id'],5,60);if(!$limit['allowed'])return $this->rateLimited($limit['retry_after']);if($this->accounts->hasWebPassword($accountId))return new \WP_REST_Response(['code'=>'web_credentials_already_configured'],409);
        $input=$request->get_json_params();$input=is_array($input)?$input:[];$password=(string)($input['password']??'');$confirmation=(string)($input['password_confirmation']??'');if(strlen($password)<12||strlen($password)>256)return new \WP_REST_Response(['code'=>'invalid_web_password'],400);if(!hash_equals($password,$confirmation))return new \WP_REST_Response(['code'=>'password_confirmation_mismatch'],400);
        if(!$this->accounts->setWebPassword($accountId,$password))return new \WP_REST_Response(['code'=>'web_password_unavailable'],500);
        return new \WP_REST_Response(['configured'=>true,'contact_email_configured'=>!empty(($this->accounts->get($accountId)['email']??'')),'identity_user_id'=>(int)($this->accounts->get($accountId)['wp_user_id']??0)],200);
    }
    public function login(\WP_REST_Request $request): \WP_REST_Response{$ipLimit=$this->rateLimits->check('web_login_ip',$this->clientIp(),5,60);if(!$ipLimit['allowed'])return $this->rateLimited($ipLimit['retry_after']);$input=$request->get_json_params();$input=is_array($input)?$input:[];$url=trim((string)($input['site_url']??''));$password=(string)($input['password']??'');$base=$this->policy->resolveSiteUrl($url);$host=$base!==null?strtolower(rtrim((string)wp_parse_url($base,PHP_URL_HOST),'.')):'';if($host!==''){$hostLimit=$this->rateLimits->check('web_login_site',$host,5,60);if(!$hostLimit['allowed'])return $this->rateLimited($hostLimit['retry_after']);}if($base===null||$password==='')return new \WP_REST_Response(['code'=>'invalid_web_credentials'],401);$site=$this->sites->findByHost($host);$account=$site?$this->accounts->get((int)$site['account_id']):null;if(!$site||!$account||$site['status']!=='active'||!$this->accounts->verifyWebPassword((int)$account['id'],$password))return new \WP_REST_Response(['code'=>'invalid_web_credentials'],401);$session=$this->webSessions->issue((int)$account['id'],(int)$site['id']);if(!$session)return new \WP_REST_Response(['code'=>'web_session_creation_failed'],500);return new \WP_REST_Response(['session'=>$session['token'],'expires_at'=>gmdate('Y-m-d H:i:s',$session['expires_at']),'account_id'=>(int)$account['id'],'site_id'=>(int)$site['id']],200);}
    public function logout(\WP_REST_Request $request): \WP_REST_Response{return new \WP_REST_Response(['revoked'=>$this->webSessions->revoke((string)$request->get_header('X-WooGit-Web-Session'))],200);}
    public function me(\WP_REST_Request $request): \WP_REST_Response{$context=$this->webContext($request);if($context instanceof \WP_REST_Response)return $context;$account=$context['account'];$site=$context['site'];return new \WP_REST_Response(['account_id'=>(int)$account['id'],'contact_email'=>$account['email'],'identity_user_id'=>(int)($account['wp_user_id']??0),'site_id'=>(int)$site['id'],'site_url'=>$site['canonical_url'],'web_password_configured'=>$this->accounts->hasWebPassword((int)$account['id']),'session_expires_at'=>gmdate('Y-m-d H:i:s',$context['session']['expires_at'])],200);}
    public function updateContactEmail(\WP_REST_Request $request): \WP_REST_Response{$context=$this->webContext($request);if($context instanceof \WP_REST_Response)return $context;$limit=$this->rateLimits->check('web_contact_email',(string)$context['account']['id'],10,60);if(!$limit['allowed'])return $this->rateLimited($limit['retry_after']);$input=$request->get_json_params();$email=is_array($input)?sanitize_email((string)($input['email']??'')):'';if($email!==''&&!is_email($email))return new \WP_REST_Response(['code'=>'invalid_contact_email'],400);if(!$this->accounts->updateContactEmail((int)$context['account']['id'],$email))return new \WP_REST_Response(['code'=>'contact_email_unavailable'],500);return new \WP_REST_Response(['contact_email'=>$email!==''?$email:null],200);}
    public function changePassword(\WP_REST_Request $request): \WP_REST_Response{$context=$this->webContext($request);if($context instanceof \WP_REST_Response)return $context;$accountId=(int)$context['account']['id'];$limit=$this->rateLimits->check('web_password_change',(string)$accountId,5,60);if(!$limit['allowed'])return $this->rateLimited($limit['retry_after']);$input=$request->get_json_params();$input=is_array($input)?$input:[];$current=(string)($input['current_password']??'');$password=(string)($input['password']??'');$confirmation=(string)($input['password_confirmation']??'');if($current===''||!$this->accounts->verifyWebPassword($accountId,$current))return new \WP_REST_Response(['code'=>'invalid_current_password'],401);if(strlen($password)<12||strlen($password)>256)return new \WP_REST_Response(['code'=>'invalid_web_password'],400);if(!hash_equals($password,$confirmation))return new \WP_REST_Response(['code'=>'password_confirmation_mismatch'],400);if(!$this->accounts->setWebPassword($accountId,$password))return new \WP_REST_Response(['code'=>'web_password_unavailable'],500);$this->webSessions->revokeAllForAccount($accountId);return new \WP_REST_Response(['changed'=>true],200);}
    public function paymentHistory(\WP_REST_Request $request): \WP_REST_Response{$context=$this->webContext($request);if($context instanceof \WP_REST_Response)return $context;$limit=$this->rateLimits->check('web_billing_history',(string)$context['account']['id'],30,60);if(!$limit['allowed'])return $this->rateLimited($limit['retry_after']);$page=max(1,(int)$request->get_param('page'));$perPage=min(50,max(1,(int)($request->get_param('per_page')?:20)));return new \WP_REST_Response($this->billing->getPaymentHistory((int)$context['account']['id'],(int)$context['site']['id'],$page,$perPage),200);}
    private function webBootstrapFailure(string $key,string $operationId,string $code,int $status,string $reason='',int $accountId=0,int $siteId=0): \WP_REST_Response{$body=['code'=>$code];if($reason!=='')$body['reason']=$reason;if($accountId>0&&$siteId>0)$this->operations->update($accountId,$siteId,$operationId,'failed',$status,$body);if(!$this->idempotency->completeVerify($key,$status,$body))$this->idempotency->markVerifyUnknown($key);return new \WP_REST_Response($body,$status);}
    private function apiContext(\WP_REST_Request $request): array|\WP_REST_Response{$session=$this->sessions->authenticate((string)$request->get_header('X-WooGit-Session'));if($session===null)return new \WP_REST_Response(['code'=>'invalid_session'],401);$account=$this->accounts->get((int)$session['account_id']);if(!$account)return new \WP_REST_Response(['code'=>'account_inactive'],403);$site=$this->sites->getOwned((int)$session['account_id'],(int)$session['site_id']);if(!$site)return new \WP_REST_Response(['code'=>'site_not_owned'],403);return ['account_id'=>(int)$account['id'],'site_id'=>(int)$site['id'],'scope'=>(string)($session['scope']??'')];}
    private function webContext(\WP_REST_Request $request): array|\WP_REST_Response{$session=$this->webSessions->authenticate((string)$request->get_header('X-WooGit-Web-Session'));if($session===null)return new \WP_REST_Response(['code'=>'invalid_web_session'],401);$account=$this->accounts->get((int)$session['account_id']);$site=$this->sites->getOwned((int)$session['account_id'],(int)$session['site_id']);if(!$account||!$site)return new \WP_REST_Response(['code'=>'account_unavailable'],403);return ['session'=>$session,'account'=>$account,'site'=>$site];}
    private function rateLimited(int $retryAfter): \WP_REST_Response{$retryAfter=max(1,$retryAfter);$response=new \WP_REST_Response(['code'=>'RATE_LIMITED','retry_after'=>$retryAfter,'retryable'=>true],429);$response->header('Retry-After',(string)$retryAfter);return $response;}
    private function clientIp(): string{$ip=isset($_SERVER['REMOTE_ADDR'])?trim((string)$_SERVER['REMOTE_ADDR']):'';return filter_var($ip,FILTER_VALIDATE_IP)?$ip:'unknown';}
}
