<?php
if(!defined('ABSPATH'))exit;
function woogit_theme_setup(){load_theme_textdomain('woogit',WOOGIT_THEME_DIR.'/languages');add_theme_support('title-tag');add_theme_support('post-thumbnails');add_theme_support('html5',['search-form','comment-form','comment-list','gallery','caption','style','script']);add_theme_support('custom-logo',['height'=>80,'width'=>240,'flex-height'=>true,'flex-width'=>true]);register_nav_menus(['primary'=>'Primary Navigation','footer'=>'Footer Navigation']);}
function woogit_asset_version($relative){$path=WOOGIT_THEME_DIR.$relative;return file_exists($path)?(string)filemtime($path):WOOGIT_THEME_VERSION;}
function woogit_enqueue_assets(){wp_enqueue_style('woogit-foundation',WOOGIT_THEME_URI.'/assets/css/foundation.css',[],woogit_asset_version('/assets/css/foundation.css'));wp_enqueue_style('woogit-components',WOOGIT_THEME_URI.'/assets/css/components.css',['woogit-foundation'],woogit_asset_version('/assets/css/components.css'));wp_enqueue_style('woogit-pages',WOOGIT_THEME_URI.'/assets/css/pages.css',['woogit-components'],woogit_asset_version('/assets/css/pages.css'));wp_enqueue_style('woogit-responsive',WOOGIT_THEME_URI.'/assets/css/responsive.css',['woogit-pages'],woogit_asset_version('/assets/css/responsive.css'));wp_enqueue_style('woogit-polish',WOOGIT_THEME_URI.'/assets/css/theme-polish.css',['woogit-responsive'],woogit_asset_version('/assets/css/theme-polish.css'));wp_enqueue_script('woogit-core',WOOGIT_THEME_URI.'/assets/js/core.js',[],woogit_asset_version('/assets/js/core.js'),true);wp_enqueue_script('woogit-navigation',WOOGIT_THEME_URI.'/assets/js/navigation.js',['woogit-core'],woogit_asset_version('/assets/js/navigation.js'),true);$slug=is_page()?get_post_field('post_name',get_queried_object_id()):'';if(in_array($slug,['login','register'],true))wp_enqueue_script('woogit-auth',WOOGIT_THEME_URI.'/assets/js/auth.js',['woogit-core'],woogit_asset_version('/assets/js/auth.js'),true);if(woogit_is_portal()||$slug==='pricing')wp_enqueue_script('woogit-portal',WOOGIT_THEME_URI.'/assets/js/portal.js',['woogit-core'],woogit_asset_version('/assets/js/portal.js'),true);wp_localize_script('woogit-core','WooGitTheme',['restUrl'=>esc_url_raw(rest_url('woogit/v1/')),'nonce'=>wp_create_nonce('wp_rest'),'authAjax'=>admin_url('admin-ajax.php'),'authNonce'=>wp_create_nonce('woogit_web_auth'),'portalNonce'=>wp_create_nonce('woogit_portal'),'home'=>home_url('/'),'loginUrl'=>woogit_page_url('login'),'portalUrl'=>woogit_page_url('portal')]);}
function woogit_provision_page($slug,$title,$content=''){$page=get_page_by_path($slug);if($page)return (int)$page->ID;$id=wp_insert_post(['post_type'=>'page','post_status'=>'publish','post_title'=>$title,'post_name'=>$slug,'post_content'=>$content,'comment_status'=>'closed','ping_status'=>'closed'],true);return is_wp_error($id)?0:(int)$id;}
function woogit_provision_pages(){
  $pages=[
    'home'=>['خانه',''],'features'=>['قابلیت‌ها',''],'how-it-works'=>['نحوه کار',''],'pricing'=>['قیمت‌گذاری',''],'faq'=>['سؤالات متداول',''],'download'=>['دریافت WooGit',''],
    'documentation'=>['راهنمای WooGit','<p>در اینجا با امکانات WooGit و نحوه استفاده از آن برای مدیریت روزمره فروشگاه آشنا می‌شوید.</p><h2>شروع کار</h2><ol><li>حساب WooGit خود را بسازید.</li><li>اشتراک مناسب فروشگاهتان را انتخاب کنید.</li><li>فروشگاه ووکامرس خود را متصل کنید.</li><li>اپلیکیشن WooGit را دریافت کنید و مدیریت فروشگاه را شروع کنید.</li></ol><h2>با WooGit چه کارهایی انجام می‌دهید؟</h2><ul><li>سفارش‌های فروشگاه را مشاهده و مدیریت می‌کنید.</li><li>محصولات را بررسی، اضافه و ویرایش می‌کنید.</li><li>وضعیت فروشگاه را از موبایل دنبال می‌کنید.</li><li>برای سفارش‌های جدید سریع‌تر باخبر می‌شوید.</li></ul>'],
    'support'=>['پشتیبانی','<p>در استفاده از WooGit به کمک نیاز دارید؟ ابتدا سؤال‌های متداول را ببینید و اگر پاسخ خود را پیدا نکردید، با پشتیبانی در ارتباط شوید.</p><div class="wg-grid wg-grid--2"><div class="wg-card"><h2>اتصال فروشگاه</h2><p>اگر در اتصال فروشگاه مشکل دارید، آدرس سایت و اطلاعاتی را که هنگام اتصال وارد کرده‌اید بررسی کنید.</p></div><div class="wg-card"><h2>اشتراک و پرداخت</h2><p>برای مشاهده اشتراک، پرداخت‌ها و صورتحساب‌های خود وارد حساب WooGit شوید.</p></div></div>'],
    'service-status'=>['وضعیت سرویس','<p>در این صفحه می‌توانید وضعیت سرویس‌های WooGit را بررسی کنید.</p><p>اگر وضعیت خاصی اعلام نشده باشد، از اطلاعات نمایش‌داده‌شده در حساب خود برای پیگیری وضعیت استفاده کنید.</p>'],
    'privacy'=>['حریم خصوصی','<h2>اطلاعات شما</h2><p>ما برای ارائه و بهبود سرویس WooGit، اطلاعات لازم برای حساب کاربری، اتصال فروشگاه، اشتراک و استفاده از سرویس را پردازش می‌کنیم.</p><h2>اطلاعات فروشگاه</h2><p>دسترسی‌های لازم فقط برای امکاناتی استفاده می‌شوند که با استفاده از WooGit در اختیار شما قرار می‌گیرند.</p><h2>حفاظت از حساب</h2><p>اطلاعات ورود خود را در اختیار دیگران قرار ندهید و برای مدیریت حساب فقط از مسیرهای رسمی WooGit استفاده کنید.</p>'],
    'terms'=>['قوانین و شرایط','<h2>استفاده از WooGit</h2><p>با استفاده از WooGit، شرایط استفاده از سرویس و قوانین مربوط به اشتراک خود را می‌پذیرید.</p><h2>اشتراک</h2><p>هر اشتراک، امکانات و مدت اعتبار مشخصی دارد که هنگام انتخاب پلن به شما نمایش داده می‌شود.</p><h2>پرداخت</h2><p>پرداخت و وضعیت اشتراک بر اساس اطلاعات سفارش و حساب شما انجام می‌شود.</p><h2>استفاده مسئولانه</h2><p>لطفاً اطلاعات حساب خود را ایمن نگه دارید و از استفاده غیرمجاز از سرویس خودداری کنید.</p>'],
    'login'=>['ورود',''],'register'=>['اتصال فروشگاه',''],'portal'=>['پرتال',''],'subscription'=>['اشتراک',''],'billing'=>['صورتحساب',''],'payments'=>['پرداخت‌ها',''],'connected-site'=>['فروشگاه متصل',''],'account-security'=>['حساب و امنیت',''],'payment-result'=>['نتیجه پرداخت','']
  ];foreach($pages as $slug=>$page)woogit_provision_page($slug,$page[0],$page[1]);
}
add_action('after_switch_theme','woogit_provision_pages');
function woogit_support_enamad_content($content){if(!is_page('support')||!in_the_loop()||!is_main_query())return $content;$s=woogit_enamad_settings();if(empty($s['enabled'])||($s['placement']??'footer')!=='contact')return $content;$o=woogit_theme_options();$img=woogit_theme_image($o['enamad_image_id']??0,'medium');$html='<section class="wg-enamad wg-contact-enamad" aria-label="نماد اعتماد الکترونیکی"><h3>اعتماد و احراز هویت</h3>';if($img){$image='<img src="'.esc_url($img).'" alt="'.esc_attr($s['alt_text']?:'نماد اعتماد الکترونیکی').'" loading="lazy" width="120" height="120">';$html.=$s['verification_url']?'<a href="'.esc_url($s['verification_url']).'" target="_blank" rel="noopener noreferrer">'.$image.'</a>':$image;}elseif($s['verification_url'])$html.='<a class="wg-badge" href="'.esc_url($s['verification_url']).'" target="_blank" rel="noopener noreferrer">مشاهده نماد اعتماد</a>';return $content.$html.'</section>';}
add_filter('the_content','woogit_support_enamad_content',20);
