<?php
if(!defined('ABSPATH'))exit;
function woogit_theme_setup(){load_theme_textdomain('woogit',WOOGIT_THEME_DIR.'/languages');add_theme_support('title-tag');add_theme_support('post-thumbnails');add_theme_support('html5',['search-form','comment-form','comment-list','gallery','caption','style','script']);add_theme_support('custom-logo',['height'=>80,'width'=>240,'flex-height'=>true,'flex-width'=>true]);register_nav_menus(['primary'=>'Primary Navigation','footer'=>'Footer Navigation']);}
function woogit_asset_version($relative){$path=WOOGIT_THEME_DIR.$relative;return file_exists($path)?(string)filemtime($path):WOOGIT_THEME_VERSION;}
function woogit_enqueue_assets(){wp_enqueue_style('woogit-foundation',WOOGIT_THEME_URI.'/assets/css/foundation.css',[],woogit_asset_version('/assets/css/foundation.css'));wp_enqueue_style('woogit-components',WOOGIT_THEME_URI.'/assets/css/components.css',['woogit-foundation'],woogit_asset_version('/assets/css/components.css'));wp_enqueue_style('woogit-pages',WOOGIT_THEME_URI.'/assets/css/pages.css',['woogit-components'],woogit_asset_version('/assets/css/pages.css'));wp_enqueue_style('woogit-responsive',WOOGIT_THEME_URI.'/assets/css/responsive.css',['woogit-pages'],woogit_asset_version('/assets/css/responsive.css'));wp_enqueue_style('woogit-polish',WOOGIT_THEME_URI.'/assets/css/theme-polish.css',['woogit-responsive'],woogit_asset_version('/assets/css/theme-polish.css'));wp_enqueue_script('woogit-core',WOOGIT_THEME_URI.'/assets/js/core.js',[],woogit_asset_version('/assets/js/core.js'),true);wp_enqueue_script('woogit-navigation',WOOGIT_THEME_URI.'/assets/js/navigation.js',['woogit-core'],woogit_asset_version('/assets/js/navigation.js'),true);$slug=is_page()?get_post_field('post_name',get_queried_object_id()):'';if(in_array($slug,['login','register'],true))wp_enqueue_script('woogit-auth',WOOGIT_THEME_URI.'/assets/js/auth.js',['woogit-core'],woogit_asset_version('/assets/js/auth.js'),true);if(woogit_is_portal()||$slug==='pricing')wp_enqueue_script('woogit-portal',WOOGIT_THEME_URI.'/assets/js/portal.js',['woogit-core'],woogit_asset_version('/assets/js/portal.js'),true);wp_localize_script('woogit-core','WooGitTheme',['restUrl'=>esc_url_raw(rest_url('woogit/v1/')),'nonce'=>wp_create_nonce('wp_rest'),'authAjax'=>admin_url('admin-ajax.php'),'authNonce'=>wp_create_nonce('woogit_web_auth'),'portalNonce'=>wp_create_nonce('woogit_portal'),'home'=>home_url('/'),'loginUrl'=>woogit_page_url('login'),'portalUrl'=>woogit_page_url('portal')]);}

function woogit_provision_page($slug,$title,$content=''){$page=get_page_by_path($slug);if($page)return (int)$page->ID;$id=wp_insert_post(['post_type'=>'page','post_status'=>'publish','post_title'=>$title,'post_name'=>$slug,'post_content'=>$content,'comment_status'=>'closed','ping_status'=>'closed'],true);return is_wp_error($id)?0:(int)$id;}
function woogit_provision_pages(){
  $pages=[
    'home'=>['خانه',''],'features'=>['قابلیت‌ها',''],'how-it-works'=>['نحوه کار',''],'pricing'=>['قیمت‌گذاری',''],'faq'=>['سؤالات متداول',''],
    'documentation'=>['مستندات','<p>راهنمای WooGit بر اساس معماری و قراردادهای رسمی سرویس ارائه می‌شود.</p><h2>شروع سریع</h2><ol><li>WooGit را روی فروشگاه خود آماده کنید.</li><li>از مسیر اتصال وب، آدرس سایت و اطلاعات لازم را وارد کنید.</li><li>Backend هویت و مالکیت سایت را بررسی می‌کند.</li><li>پس از تأیید، وضعیت حساب و سرویس را در پرتال دنبال کنید.</li></ol><h2>مرزهای سرویس</h2><p>Theme وب برای وب‌سایت رسمی و Customer Portal است و به Customer WooCommerce برای عملیات فروشگاه متصل نمی‌شود.</p>'],
    'support'=>['پشتیبانی','<p>اگر در اتصال، ورود یا مشاهده وضعیت سرویس مشکلی دارید، ابتدا وضعیت سرویس را بررسی کنید و سپس از مسیر پشتیبانی برای پیگیری استفاده کنید. اطلاعات محرمانه را در پیام عمومی ارسال نکنید.</p><div class="wg-grid wg-grid--2"><div class="wg-card"><h2>اتصال و ورود</h2><p>آدرس سایت و جریان Web Bootstrap را بررسی کنید. Credentialها فقط در مسیر رسمی و موردنیاز ارسال شوند.</p></div><div class="wg-card"><h2>پرداخت و اشتراک</h2><p>وضعیت سفارش و پرداخت از منبع تجاری WooGit بررسی می‌شود؛ نتیجه بازگشت پرداخت به‌تنهایی اثبات پرداخت نیست.</p></div></div>'],
    'service-status'=>['وضعیت سرویس','<p>این صفحه محل نمایش وضعیت سرویس‌های عمومی WooGit است. اگر منبع وضعیت زنده فعال نباشد، رابط کاربری وضعیت ساختگی تولید نمی‌کند.</p>'],
    'privacy'=>['حریم خصوصی','<h2>اصل حداقل‌سازی داده</h2><p>اطلاعات فقط برای ارائه سرویس، احراز هویت، مدیریت نشست وب و عملیات قراردادی لازم پردازش می‌شوند.</p><h2>اطلاعات حساس</h2><p>Credentialهای WordPress/WooCommerce در Theme نگهداری دائمی نمی‌شوند و نباید در log، cookie نامناسب، HTML، JavaScript یا telemetry ذخیره شوند.</p><h2>نشست وب</h2><p>نشست وب با شناسه مستقل از نشست اپلیکیشن مدیریت می‌شود.</p>'],
    'terms'=>['قوانین و شرایط','<h2>استفاده از سرویس</h2><p>استفاده از WooGit باید مطابق قوانین و قرارداد سرویس انجام شود.</p><h2>پرداخت و دسترسی</h2><p>قیمت، وضعیت پرداخت و entitlement از منابع authoritative سرویس خوانده می‌شوند و رابط کاربری آن‌ها را جعل یا محاسبه نمی‌کند.</p><h2>امنیت</h2><p>از ارسال اطلاعات محرمانه در کانال‌های عمومی خودداری کنید و اطلاعات حساب را فقط در مسیرهای رسمی وارد کنید.</p>'],
    'login'=>['ورود',''],'register'=>['اتصال فروشگاه',''],'portal'=>['پرتال',''],'subscription'=>['اشتراک',''],'billing'=>['صورتحساب',''],'payments'=>['پرداخت‌ها',''],'connected-site'=>['فروشگاه متصل',''],'account-security'=>['حساب و امنیت',''],'payment-result'=>['نتیجه پرداخت','']
  ];
  foreach($pages as $slug=>$page)woogit_provision_page($slug,$page[0],$page[1]);
}
add_action('after_switch_theme','woogit_provision_pages');

function woogit_support_enamad_content($content){if(!is_page('support')||!in_the_loop()||!is_main_query())return $content;$s=woogit_enamad_settings();if(empty($s['enabled'])||($s['placement']??'footer')!=='contact')return $content;$o=woogit_theme_options();$img=woogit_theme_image($o['enamad_image_id']??0,'medium');$html='<section class="wg-enamad wg-contact-enamad" aria-label="نماد اعتماد الکترونیکی"><h3>اعتماد و احراز هویت</h3>';if($img){$image='<img src="'.esc_url($img).'" alt="'.esc_attr($s['alt_text']?:'نماد اعتماد الکترونیکی').'" loading="lazy" width="120" height="120">';$html.=$s['verification_url']?'<a href="'.esc_url($s['verification_url']).'" target="_blank" rel="noopener noreferrer">'.$image.'</a>':$image;}elseif($s['verification_url'])$html.='<a class="wg-badge" href="'.esc_url($s['verification_url']).'" target="_blank" rel="noopener noreferrer">مشاهده نماد اعتماد</a>';return $content.$html.'</section>';}
add_filter('the_content','woogit_support_enamad_content',20);
