#!/usr/bin/env bash
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"; THEME="$ROOT/theme/woogit"; FAIL=0
pass(){ printf 'PASS: %s\n' "$1"; }; fail(){ printf 'FAIL: %s\n' "$1"; FAIL=1; }
for dir in "$THEME/templates/public" "$THEME/templates/auth" "$THEME/templates/portal" "$THEME/template-parts"; do [[ -d "$dir" ]]&&pass "required template directory exists: ${dir#$THEME/}"||fail "missing required template directory: ${dir#$THEME/}"; done
for file in "$THEME/templates/public/home.php" "$THEME/templates/public/payment-result.php" "$THEME/templates/auth/login.php" "$THEME/templates/auth/register.php" "$THEME/templates/portal/overview.php" "$THEME/templates/portal/subscription.php" "$THEME/templates/portal/billing.php" "$THEME/templates/portal/payments.php" "$THEME/templates/portal/connected-site.php" "$THEME/templates/portal/account-security.php"; do [[ -f "$file" ]]&&pass "required template exists: ${file#$THEME/}"||fail "missing required template: ${file#$THEME/}"; done
if grep -RInE 'wp_remote_(get|post|request)\(|\$wpdb|WC_[A-Za-z_]+' "$THEME/templates" "$THEME/template-parts"; then fail 'templates/template-parts contain direct infrastructure access'; else pass 'templates/template-parts stay presentation-only'; fi
# Boundary scan: only executable Theme code is inspected; public presentation copy may name the App/Web session headers for documentation.
if grep -RInE 'activate-session|X-WooGit-Session' "$THEME/inc" "$THEME/assets/js" "$THEME/assets/css" --include='*.php' --include='*.js' --include='*.css'; then fail 'executable Theme code references App session or activate-session'; else pass 'executable Theme code does not consume App session'; fi
for forbidden in 'update_option.*consumer_secret' 'set_transient.*consumer_secret' 'setcookie.*consumer_secret' 'wp_localize_script.*consumer_secret' 'localStorage.*consumer_secret' 'sessionStorage.*consumer_secret'; do grep -RInE "$forbidden" "$THEME" --include='*.php' --include='*.js'&&fail "credential persistence pattern found: $forbidden"||pass "no credential persistence pattern: $forbidden"; done
for page in page-features.php page-how-it-works.php page-faq.php page-documentation.php page-support.php page-service-status.php page-privacy.php page-terms.php; do [[ -f "$THEME/$page" ]]&&grep -q "template-parts/public-page.php" "$THEME/$page"&&pass "$page uses shared public renderer"||fail "$page is missing or does not use shared public renderer"; done
grep -RInE "billing/activate-session|['\"]activate-session['\"]" "$THEME/inc" "$THEME/assets" "$THEME/page*.php" --include='*.php' --include='*.js' --include='*.css'&&fail 'Theme billing surface references App-only activation endpoint'||pass 'Theme billing surface excludes App-only activation'
# Web Password is intentionally not collected during Bootstrap. It is configured after successful verification on Account / Security.
REGISTER="$THEME/templates/auth/register.php"
if grep -q 'data-multistep' "$REGISTER"&&grep -q 'data-step="4"' "$REGISTER"; then pass 'register is a four-step Bootstrap flow'; else fail 'register Bootstrap flow is incomplete'; fi
if grep -Eiq 'web_password|رمز عبور وب|12.?256|۱۲.?۲۵۶|invalid_web_password' "$REGISTER"; then fail 'register template still contains Web Password collection/validation'; else pass 'register template contains no Web Password collection/validation'; fi
if grep -q 'data-woogit-portal-action="setup_web_credentials"' "$THEME/templates/portal/account-security.php"&&grep -q 'minlength="12"' "$THEME/templates/portal/account-security.php"&&grep -q 'maxlength="256"' "$THEME/templates/portal/account-security.php"; then pass 'post-bootstrap Web Password setup has 12–256 character contract'; else fail 'post-bootstrap Web Password setup contract is incomplete'; fi
if grep -q 'data-woogit-auth="register"' "$REGISTER"&&grep -q "\['wp_username','wp_application_password','consumer_key','consumer_secret'\]" "$THEME/functions.php"; then pass 'register AJAX contract contains only store verification credentials'; else fail 'register AJAX contract still includes Web Password'; fi
if grep -q 'invalid_web_password' "$THEME/assets/js/auth.js"; then fail 'auth.js exposes invalid_web_password as a registration error'; else pass 'auth.js does not expose Web Password validation as a registration error'; fi
grep -q 'id="wg-home-preview"' "$THEME/templates/public/home.php"&&pass 'home contains app preview markup'||fail 'home app preview missing'
grep -q "templates/portal/' . \$portal_templates\[\$slug\]" "$THEME/page.php"&&grep -q "templates/auth/login" "$THEME/page.php"&&grep -q "templates/auth/register" "$THEME/page.php"&&pass 'WordPress page routing delegates to V1 templates'||fail 'page.php does not delegate V1 page routes correctly'
grep -q 'woogit_commerce_payment_order' "$THEME/templates/public/payment-result.php"&&pass 'payment return uses scoped WooCommerce adapter'||fail 'payment return is not backed by scoped order adapter'
# Entitlement authority belongs to the Backend. The Theme return page may read the backend billing status to
# present the final state, but it must not reconcile/activate entitlement itself. App reconciliation happens after
# the WebView closes. Keep this test aligned with that boundary instead of requiring an activation side effect.
grep -q 'billing/status' "$THEME/templates/public/payment-result.php"&&grep -q 'entitlement_active' "$THEME/templates/public/payment-result.php"&&grep -q "entitlement === 'active'" "$THEME/templates/public/payment-result.php"&&pass 'payment return reads backend entitlement state without reconciling it'||fail 'payment return entitlement-state handling is missing'
grep -q 'woogit_commerce_payment_method' "$THEME/inc/portal/data.php"&&pass 'payment method selection uses deterministic adapter rule'||fail 'payment method selection rule missing'
grep -q 'theme-polish.css' "$THEME/inc/setup/theme.php"&&pass 'semantic theme polish stylesheet is enqueued'||fail 'semantic theme polish stylesheet missing from enqueue'
grep -q 'WooGit.errorMessage' "$THEME/assets/js/core.js"&&pass 'central API error mapping exists'||fail 'central API error mapping missing'
grep -q 'focusables' "$THEME/assets/js/navigation.js"&&grep -q "e.key==='Escape'" "$THEME/assets/js/navigation.js"&&pass 'mobile navigation has focus trap and Escape handling'||fail 'mobile navigation accessibility handling incomplete'
grep -q 'data-price' "$THEME/page-pricing.php"&&grep -q 'data-woogit-variation-select' "$THEME/page-pricing.php"&&pass 'pricing exposes variation price metadata'||fail 'pricing variation metadata missing'
grep -q "\['placement'\]==='footer'" "$THEME/footer.php"&&pass 'Enamad footer placement is explicit'||fail 'Enamad footer placement handling missing'
grep -q 'woogit_support_enamad_content' "$THEME/inc/setup/theme.php"&&grep -q "\['placement'\].*contact" "$THEME/inc/setup/theme.php"&&pass 'Enamad contact placement is rendered through content filter'||fail 'Enamad contact placement handling missing'
exit "$FAIL"
